src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliations</relationshipLabel>
        <relationshipName>Reconciliations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Credits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Debits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReconciliationTestClass.cls
@isTest
private class ReconciliationTestClass {

    static testMethod void testReconciliationValidation() {
        
        Account account = new Account(Name = 'Test Account', Auto_Reconcile__c = true);
        insert account;
        
        Reconciliation__c reconciliation = new Reconciliation__c(
        	Account__c = account.Id
        );
        insert reconciliation;
        
        reconciliation.Credits__c = 10;
        reconciliation.Reconciled__c = true;
        
        try {
        	update reconciliation;
        	system.assert(false);
        } catch (DMLException e) {
        	
        }
        
        Reconciliation__c reconciliation2 = new Reconciliation__c(
        	Account__c = account.Id,
        	Credits__c = 10
        );
        
        try {
        	insert reconciliation2;
        	system.assert(false);
        } catch (DMLException e) {
        	
        }
        
        Reconciliation__c reconciliation3 = new Reconciliation__c(
        	Account__c = account.Id,
        	Debits__c = 10
        );
        
        try {
        	insert reconciliation3;
        	system.assert(false);
        } catch (DMLException e) {
        	
        }
        
        
    }
}