src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Unallocated__c</fullName>
        <formula>Subtotal__c  - Amount_Allocated__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Unallocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>Date__c + Payment_Term__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Subtotal__c</fullName>
        <label>Subtotal</label>
        <summarizedField>Fiscal_Document_Line__c.Net_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(RecordType.DeveloperName == &apos;sales_invoice&apos;,
    IF(Amount_Allocated__c == Subtotal__c, &apos;Paid&apos;,
      IF(Amount_Allocated__c == 0, &apos;Open&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Paid&apos;, &apos;&apos;)
      )
      &amp;
      IF( Due_Date__c &lt; DATEVALUE(NOW()), IF( Actual_Due_Date__c &gt;= DATEVALUE(NOW()), &apos; - Overdue (Buffer)&apos;, &apos; - Overdue&apos;), &apos;&apos;)
    ),
    IF(Amount_Allocated__c == Subtotal__c, &apos;Allocated&apos;,
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Allocated&apos;, &apos;&apos;)
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtotal_Value__c</fullName>
        <formula>Net_Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Total</label>
        <summarizedField>Fiscal_Document_Line__c.Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tax_Subtotal__c</fullName>
        <label>Tax</label>
        <summarizedField>Fiscal_Document_Line__c.Tax_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tax_Value__c</fullName>
        <formula>Tax_Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>credit_note</fullName>
        <active>true</active>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Subtotal__c</fullName>
        <formula>Subtotal__c - Tax_Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subtotal_Value__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <formula>Amount__c * (1 + Tax_Rate__c) * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Subtotal__c</fullName>
        <formula>Amount__c * Tax_Rate__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fiscal Document Line</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Document Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>IF(
  NOT(ISNULL(Fiscal_Document__r.Date__c)),
  Fiscal_Document__r.Date__c,
  IF(
    NOT(ISNULL(Payment__r.Date__c)),
    Payment__r.Date__c,
    IF(
      NOT(ISNULL(Refund__r.Date__c)),
      Refund__r.Date__c,
      null
    )
  )
)</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;, IF(Reconciled__c == True, &apos;Allocated&apos;, &apos;Unallocated&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(Failed__c == True, &apos;Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Paid - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliations</relationshipLabel>
        <relationshipName>Reconciliations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
IF(Failed__c == True, &apos;Failed&apos;,
  IF(Payment_Failed__c == True, &apos;Payment Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Confirmed - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FiscalDocumentsController.cls
public class FiscalDocumentsController {
    private ApexPages.StandardController stdController;
    private Fiscal_Document__c fiscal_document;
    public Account account {get;set;}
    public Payment__c relatedPayment;
    public List<String> addressComponents {get;set;}
    
    public List<Ledger_Item__c> credit_notes {get; set;}
    public List<Ledger_Item__c> payments {get; set;}
    public List<Ledger_Item__c> invoices {get; set;}
    public List<Ledger_Item__c> refunds {get; set;}
    public Boolean renderPayments {get; set;}
    public Boolean renderCreditNotes {get; set;}
    public Boolean renderInvoices {get; set;}
    public Boolean renderRefunds {get; set;}
    
    public Decimal totalInvoicesAllocated {get; set;}
    public Decimal totalCreditNotesAllocated {get; set;}
    public Decimal totalPaymentsAllocated {get; set;}
    public Decimal totalRefundsAllocated {get; set;}
    
    public Decimal outstandingInvoiceTotal {get; set;}
    public Decimal currentInvoiceTotal {get; set;}
    public Decimal amountPaid {get; set;}
    
    public Id selReconciliation {get;set;}
    
    public List<Fiscal_Document__c> openInvoices {get; set;}
    
    public FiscalDocumentsController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.fiscal_document = (Fiscal_Document__c)this.stdController.getRecord();
        this.addressComponents = new List<String>();
        this.payments = new List<Ledger_Item__c>();
        this.credit_notes = new List<Ledger_Item__c>();
        this.openInvoices = new List<Fiscal_Document__c>();
        if (this.fiscal_document.Id != null) {
                Fiscal_Document__c fd = (Fiscal_Document__c)[SELECT Id, Account__c, Amount_Allocated__c, Subtotal__c FROM Fiscal_Document__c WHERE Id = :this.fiscal_document.Id];
                this.fiscal_document.Amount_Allocated__c = fd.Amount_Allocated__c;
                //this.fiscal_document.Subtotal__c = fd.Subtotal__c;
                this.account = (Account)[SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Type, Auto_Reconcile__c FROM Account WHERE Id = :fd.Account__c];
                if (this.account != null) {
                        if (this.account.BillingStreet != null) {
                                for (String part : this.account.BillingStreet.split('\\r\\n')) {
                                this.addressComponents.add(part);
                                }
                        }
                        if (this.account.BillingCity != null) {
                            this.addressComponents.add(this.account.BillingCity);
                        }
                        if (this.account.BillingState != null) {
                            this.addressComponents.add(this.account.BillingState);
                        }
                        if (this.account.BillingPostalCode != null) {
                            this.addressComponents.add(this.account.BillingPostalCode);
                        }
                        if (this.account.BillingCountry != null) {
                            this.addressComponents.add(this.account.BillingCountry);
                        }
                }
        }
        this.totalInvoicesAllocated = 0.00;
        this.totalCreditNotesAllocated = 0.00;
        this.totalPaymentsAllocated = 0.00;
        this.totalRefundsAllocated = 0.00;
        this.outstandingInvoiceTotal = 0.00;
        this.currentInvoiceTotal = 0.00;
        this.amountPaid = 0.00;
        
        List<PriceBook2> priceBook = [SELECT Id FROM PriceBook2 WHERE IsStandard = true];
        if (priceBook.size() > 0) {
                this.fiscal_document.Price_Book__c = priceBook.get(0).Id;
        }
        
        if (this.fiscal_document.Id != null) {
            this.getLinkedLedgerItems();
            /*this.openInvoices.addAll([SELECT Id, Reference__c, Subtotal__c, Amount_Allocated__c,  Due_Date__c, Date__c, Status__c, Amount_Unallocated__c, Net_Subtotal__c, Subtotal_Value__c, Tax_Subtotal__c, Tax_Value__c FROM Fiscal_Document__c WHERE RecordType.DeveloperName = 'sales_invoice' AND Account__c = :this.account.Id AND Id != :this.fiscal_document.Id AND Status__c NOT IN('Draft','Paid')]);
            if(this.openInvoices.size() > 0) {
                for(Fiscal_Document__c fd: openInvoices) {
                    this.outstandingInvoiceTotal += fd.Amount_Unallocated__c;
                }
            }
            
            system.debug(this.fiscal_document);
            system.debug(this.currentInvoiceTotal);
            system.debug(this.outstandingInvoiceTotal);
            system.debug(this.fiscal_document.Subtotal__c);
            system.debug(this.fiscal_document.Amount_Allocated__c);
            this.currentInvoiceTotal = this.outstandingInvoiceTotal + (this.fiscal_document.Subtotal__c - this.fiscal_document.Amount_Allocated__c);
            if(this.payments.size() > 0) {
                for(Ledger_Item__c item: this.payments) {
                    this.amountPaid += item.Amount__c;
                }
            }*/
        }
    }
    
    /*public void autoProcessConfirmTrue () {
        this.fiscal_document.Auto_Actions__c = true;
        this.validateDraft();
    }
    
    public void autoProcessConfirmFalse () {
        this.fiscal_document.Auto_Actions__c = false;
        this.validateDraft();
    }*/
    
    public PageReference takePayment() {
        PageReference pg = new PageReference('/apex/PaymentTake?amount=' + String.valueOf(this.fiscal_document.Subtotal__c - this.fiscal_document.Amount_Allocated__c) + '&account=' + this.fiscal_document.Account__c + '&description=' + this.fiscal_document.Reference__c + '&documentid=' + this.fiscal_document.Id);
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference validateDraft() {
        this.fiscal_document.Draft__c = false;
        
        try {
            update this.fiscal_document;
        } catch (Exception e) {
            this.fiscal_document.Draft__c = true;
            ApexPages.addMessages(e);
            return null;
        }
        
        PageReference pg = new PageReference('/apex/FiscalDocumentActionsConfirmation?id=' + String.valueOf(this.fiscal_document.Id));
        pg.setRedirect(true);
        return pg;
        
    }
    
    public PageReference cloneFiscalDocumentToCreditNote () {
        List<Fiscal_Document_Line__c> fdlines = new List<Fiscal_Document_Line__c>();
        fdlines.addAll([SELECT Id, Amount__c, Description__c, Nominal_Code__c, Product__c, Quantity__c, Tax__c, Fiscal_Document__c FROM Fiscal_Document_Line__c WHERE Fiscal_Document__c =: this.fiscal_document.Id]);
        
        Fiscal_Document__c cloneFd = this.fiscal_document.clone(false, true, false, false);
        cloneFd.RecordTypeId = [Select Id From RecordType  Where SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'credit_note'].Id;
        cloneFd.Amount_Allocated__c = 0.00;
        cloneFd.Date__c = Date.today();
        cloneFd.Payment_Term__c = 0;
        cloneFd.Draft__c = true;
        cloneFd.Reference__c = '';
        cloneFd.Auto_Proc__c = false;
        cloneFd.Auto_Actions__c = false;
        cloneFd.Sent__c = false;
        insert cloneFd;
        
        for (Fiscal_Document_Line__c fdl: fdlines) {
            Fiscal_Document_Line__c tmpfdl = fdl.clone(false, true, false, false);
            tmpfdl.Fiscal_Document__c = cloneFd.Id;
            insert tmpfdl;
        }
        PageReference pg = new PageReference('/apex/FiscalDocumentView?id=' + String.valueOf(cloneFd.Id));
        pg.setRedirect(true);
        return pg;
    }
        
    public void getLinkedLedgerItems() {
        List<Id> reconciliationIds = new List<Id>();
        for(Ledger_Item__c item: [SELECT Id, Reconciliation__c, Reconciled__c, Fiscal_Document__r.RecordType.DeveloperName FROM Ledger_Item__c WHERE Reconciled__c = true AND Fiscal_Document__c = :fiscal_document.Id]) {
            reconciliationIds.add(item.Reconciliation__c);
        }
        if(reconciliationIds.isEmpty()) {
            return;
        }
        
        this.credit_notes = new List<Ledger_Item__c>();
        this.payments = new List<Ledger_Item__c>();
        this.invoices = new List<Ledger_Item__c>();
        this.refunds = new List<Ledger_Item__c>();
        this.renderPayments = false;
        this.renderCreditNotes = false;
        this.renderInvoices = false;
        this.renderRefunds = false;
        
        for(Ledger_Item__c item: [SELECT Id, Amount__c, Fiscal_Document__c, Fiscal_Document__r.Description__c, Fiscal_Document__r.Date__c, Fiscal_Document__r.RecordType.DeveloperName, Payment__c, Payment__r.Description__c, Payment__r.Date__c, Refund__c, Reconciliation__c FROM Ledger_Item__c WHERE Reconciliation__c IN :reconciliationIds AND Fiscal_Document__r.RecordTypeId != :this.fiscal_document.RecordTypeId]) {
            if(item.Fiscal_Document__c != null && item.Fiscal_Document__r.RecordType.DeveloperName == 'credit_note') {
                this.credit_notes.add(item);
            }
            
            if(item.Fiscal_Document__c != null && item.Fiscal_Document__r.RecordType.DeveloperName == 'sales_invoice') {
                this.invoices.add(item);
            }
            
            if(item.Payment__c != null) {
                this.payments.add(item);
            }
            
            if(item.Refund__c != null) {
                this.refunds.add(item);
            }
        }
        
        if(this.payments.size() > 0) {
            system.debug('Related Payment Ledger Items: ' + this.payments);
            this.renderPayments = true;
        }
        
        if(this.refunds.size() > 0) {
            this.renderRefunds = true;
        }
        
        if(this.credit_notes.size() > 0) {
            this.renderCreditNotes = true;
        }
        
        if(this.invoices.size() > 0) {
            this.renderInvoices = true;
        }
    }
    
    public String getTextColour() {
        if (this.account.Type == 'Residential') {
            return '#ec1c24';
        } else if (this.account.Type == 'Business' || this.account.Type == 'Reseller') {
            return '#00aff0';
        } else if (this.account.Type == 'Public Sector') {
            return '#00bb00';
        } else {
            return '#00bb00';
        }
    }
    
    public String getLogo() {
        if (this.account.Type == 'Residential') {
            return PageReference.forResource('Connexin_Home_Logo').getUrl();
        } else if (this.account.Type == 'Business' || this.account.Type == 'Reseller') {
            return PageReference.forResource('Connexin_Business_Logo').getUrl();
        } else if (this.account.Type == 'Public Sector') {
            return PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl();
        } else {
            return PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl();
        }
    }
    
    public String getFooterImage() {
        if (this.account.Type == 'Residential') {
            return PageReference.forResource('Connexin_Home_Footer').getUrl();
        } else if (this.account.Type == 'Business' || this.account.Type == 'Reseller') {
            return PageReference.forResource('Connexin_Business_Footer').getUrl();
        } else if (this.account.Type == 'Public Sector') {
            return PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl();
        } else {
            return PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl();
        }
    }
    
    public String getOddRowColour() {
        return 'white';
    }
    
    public String getEvenRowColour() {
        return '#f7f7f9';
    }
    
    public String getWebsite() {
        if (this.account.Type == 'Residential') {
            return 'home.connexin.co.uk';
        } else if (this.account.Type == 'Business' || this.account.Type == 'Reseller') {
            return 'business.connexin.co.uk';
        } else if (this.account.Type == 'Public Sector') {
            return 'smartcities.connexin.co.uk';
        } else {
            return 'smartcities.connexin.co.uk';
        }
    }
    
    public PageReference viewPdf() {
        PageReference pg = new PageReference('/apex/FiscalDocumentPDF?id=' + String.valueOf(this.fiscal_document.Id));
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference viewCsv() {
        PageReference pg = new PageReference('/apex/FiscalDocumentCSV?id=' + String.valueOf(this.fiscal_document.Id));
        pg.setRedirect(false);
        return pg;
    }
    
    public void sendEmail() {
        Contact[] contacts = [SELECT Id, Email FROM Contact WHERE AccountId = :this.fiscal_document.Account__c AND Email != null];
        
        if (contacts.size() == 0) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, this.fiscal_document.RecordType.Name + ' could not be sent - No Contacts with Email Addresses exist on the Account'));
            return;
        }
        
        Messaging.reserveSingleEmailCapacity(contacts.size());
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        String[] toAddresses = new String[]{};
        for (Contact contact: contacts) {
            toAddresses.add(contact.Email);
        }
        
        mail.setToAddresses(toAddresses);
        mail.setUseSignature(false);
        
        OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'support@connexin.co.uk'];
        if (owea.size() > 0) {
            mail.setOrgWideEmailAddressId(owea.get(0).Id);
        }
        
        mail.setSubject('Your Connexin ' + this.fiscal_document.RecordType.Name + ' - ' + this.fiscal_document.Reference__c);
        mail.setPlainTextBody('Hi,\n\nPlease find your Connexin ' + this.fiscal_document.RecordType.Name + ' attached\n\nIf you have any questions please do not hesitate to contact us\n\nKind Regards,\n\nThe Connexin Accounts Team\n01482 36 37 38');
        mail.setHtmlBody('Hi,<br /><br />Please find your Connexin ' + this.fiscal_document.RecordType.Name + ' attached<br /><br />If you have any questions please do not hesitate to contact us<br /><br />Kind Regards,<br /><br />The Connexin Accounts Team<br />01482 36 37 38<br />');
        
        PageReference pdf = Page.FiscalDocumentPDF;
        pdf.getParameters().put('id', (String)this.fiscal_document.Id);
        
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(this.fiscal_document.Reference__c + '.pdf');
        blob pdfBody;
        if(Test.isRunningTest()) { 
          pdfBody = blob.valueOf('Unit.Test');
        } else {
          pdfBody = pdf.getContent();
        }
        efa.setBody(pdfBody);
        
        PageReference csv = Page.FiscalDocumentCSV;
        csv.getParameters().put('id', (String)this.fiscal_document.Id);
        
        Messaging.EmailFileAttachment efa2 = new Messaging.EmailFileAttachment();
        efa2.setFileName(this.fiscal_document.Reference__c + '.csv');
        blob csvBody;
        if(Test.isRunningTest()) { 
          csvBody = blob.valueOf('Unit.Test');
        } else {
          csvBody = csv.getContent();
        }
        efa2.setBody(csvBody);
        
        mail.setFileAttachments(new Messaging.EmailFileAttachment[] { efa, efa2 });      
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        if (this.fiscal_document.Sent__c == false) {
            this.fiscal_document.Sent__c = true;
            update this.fiscal_document;
        }
        
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, this.fiscal_document.RecordType.Name + ' Sent to ' + String.join(toAddresses, ', ')));
    }
    
    public PageReference unreconcile() {
        Reconciliation__c tmpRecon = [SELECT Account__r.Auto_Reconcile__c FROM Reconciliation__c WHERE Id = :this.selReconciliation];
        
        if(tmpRecon.Account__r.Auto_Reconcile__c) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Cannot delete reconciliation for acounts set to reconcile automatically. Please set \'Auto Reconcile\' to disable before deleting reconciliations'));
            return null;
        }
        Reconciliation.unreconcileReconciliations(new Set<Id>{this.selReconciliation});
        
        return this.stdController.view();
    }
    
    public String getNewLine() {
        return '\n';
    }
}