src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Net_Subtotal__c</fullName>
        <label>Subtotal</label>
        <summarizedField>Fiscal_Document_Line__c.Net_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(RecordType.DeveloperName == &apos;sales_invoice&apos;,
    IF(Amount_Allocated__c == Subtotal__c, &apos;Paid&apos;,
      IF(Amount_Allocated__c == 0, &apos;Open&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Paid&apos;, &apos;&apos;)
      )
      &amp;
      IF( Due_Date__c &lt; DATEVALUE(NOW()), IF( Actual_Due_Date__c &gt;= DATEVALUE(NOW()), &apos; - Overdue (Buffer)&apos;, &apos; - Overdue&apos;), &apos;&apos;)
    ),
    IF(Amount_Allocated__c == Subtotal__c, &apos;Allocated&apos;,
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Allocated&apos;, &apos;&apos;)
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Total</label>
        <summarizedField>Fiscal_Document_Line__c.Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tax_Subtotal__c</fullName>
        <label>Tax</label>
        <summarizedField>Fiscal_Document_Line__c.Tax_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>credit_note</fullName>
        <active>true</active>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>IF(
  NOT(ISNULL(Fiscal_Document__r.Date__c)),
  Fiscal_Document__r.Date__c,
  IF(
    NOT(ISNULL(Payment__r.Date__c)),
    Payment__r.Date__c,
    IF(
      NOT(ISNULL(Refund__r.Date__c)),
      Refund__r.Date__c,
      null
    )
  )
)</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;, IF(Reconciled__c == True, &apos;Allocated&apos;, &apos;Unallocated&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Manual&quot;</defaultValue>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>go_cardless</fullName>
                </value>
                <value>
                    <fullName>stripe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(Failed__c == True, &apos;Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Paid - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliations</relationshipLabel>
        <relationshipName>Reconciliations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
IF(Failed__c == True, &apos;Failed&apos;,
  IF(Payment_Failed__c == True, &apos;Payment Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Confirmed - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReconciliationController.cls
public class ReconciliationController {
    private Reconciliation__c currReconciliation;
    private ApexPages.StandardController stdController;
    
    public Map<Id, Decimal> ledgerItems {get;set;}
    public List<Fiscal_Document__c> salesInvoiceRelations {get;set;}
    public List<Fiscal_Document__c> creditNoteRelations {get;set;}
    public List<Payment__c> paymentRelations {get;set;}
    public List<Refund__c> refundRelations {get;set;}
    
    /*public Map<Id, Boolean> removedDocuments {get; set;}
    public Map<Id, Boolean> removedPayments {get; set;}
    public Map<Id, Boolean> removedRefunds {get; set;}*/
    
    public Decimal totalInvoicesAllocated {get; set;}
    public Decimal totalCreditNotesAllocated {get; set;}
    public Decimal totalPaymentsAllocated {get; set;}
    public Decimal totalRefundsAllocated {get; set;}
    
    public ReconciliationController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.currReconciliation = (Reconciliation__c)this.stdController.getRecord();

        this.totalInvoicesAllocated = 0.00;
        this.totalCreditNotesAllocated = 0.00;
        this.totalPaymentsAllocated = 0.00;
        this.totalRefundsAllocated = 0.00;
        
        this.getRelatedParents();
        
        List<Ledger_Item__c> invoices = [SELECT Id, Fiscal_Document__c, Reconciliation__c FROM Ledger_Item__c WHERE Fiscal_Document__c != null AND Fiscal_Document__r.RecordType.DeveloperName = 'Sales_Invoice' AND Reconciliation__c = :this.currReconciliation.Id];
        List<Ledger_Item__c> creditNotes = [SELECT Id, Fiscal_Document__c FROM Ledger_Item__c WHERE Fiscal_Document__c != null AND Fiscal_Document__r.RecordType.DeveloperName = 'Credit_Note' AND Reconciliation__c = :this.currReconciliation.Id];
        List<Ledger_Item__c> payments = [SELECT Id, Payment__c FROM Ledger_Item__c WHERE Payment__c != null AND Reconciliation__c = :this.currReconciliation.Id];
        List<Ledger_Item__c> refunds = [SELECT Id, Refund__c FROM Ledger_Item__c WHERE Refund__c != null AND Reconciliation__c = :this.currReconciliation.Id];
        
        /*this.removedDocuments = new Map<Id, Boolean>();
        for(Ledger_Item__c invoice: invoices) {
            this.removedDocuments.put(invoice.Fiscal_Document__c, false);
        }
        for(Ledger_Item__c creditNote: creditNotes) {
            this.removedDocuments.put(creditNote.Fiscal_Document__c, false);
        }
        
        this.removedPayments = new Map<Id, Boolean>();
        for(Ledger_Item__c payment: payments) {
            this.removedPayments.put(payment.Payment__c, false);
        }
        
        this.removedRefunds = new Map<Id, Boolean>();
        for(Ledger_Item__c refund: refunds) {
            this.removedRefunds.put(refund.Refund__c, false);
        }*/
    }
    
    /*public List<Fiscal_Document__c> getNonReconciliedFdList() {
        List<Fiscal_Document__c> fds = [SELECT Id, Name, Net_Subtotal__c, Tax_Subtotal__c, Subtotal__c FROM Fiscal_Document__c WHERE Draft__c = false];
        return fds;
    }
    
    public List<Ledger_Item__c> getInvoices() {
        List<Ledger_Item__c> invoices= [SELECT Id, Fiscal_Document__r.Name, Fiscal_Document__r.Net_Subtotal__c, Fiscal_Document__r.Tax_Subtotal__c, Fiscal_Document__r.Subtotal__c, Fiscal_Document__r.Amount_Allocated__c  FROM Ledger_Item__c WHERE Fiscal_Document__c != null AND Fiscal_Document__r.RecordType.DeveloperName = 'Sales_Invoice' AND Reconciliation__r.Id = :this.currReconciliation.Id];
        return invoices;
    }
    
    public List<Ledger_Item__c> getCreditNotes() {
        List<Ledger_Item__c> creditnotes= [SELECT Id, Fiscal_Document__r.Name, Fiscal_Document__r.Net_Subtotal__c, Fiscal_Document__r.Tax_Subtotal__c, Fiscal_Document__r.Subtotal__c, Fiscal_Document__r.Amount_Allocated__c  FROM Ledger_Item__c WHERE Fiscal_Document__c != null AND Fiscal_Document__r.RecordType.DeveloperName = 'Credit_Note' AND Reconciliation__r.Id = :this.currReconciliation.Id];
        return creditnotes;
    }
    
    public List<Ledger_Item__c> getPayments() {
        List<Ledger_Item__c> payments= [SELECT Id, Payment__r.Name, Payment__r.Amount__c, Payment__r.Date__c,  Payment__r.Amount_Allocated__c FROM Ledger_Item__c WHERE Payment__c != null AND Reconciliation__r.Id = :this.currReconciliation.Id];
        return payments;
    }
    public List<Ledger_Item__c> getRefunds() {
        List<Ledger_Item__c> refunds= [SELECT Id, Refund__r.Name, Refund__r.Amount__c, Refund__r.Date__c, Refund__r.Amount_Allocated__c FROM Ledger_Item__c WHERE Refund__c != null AND Reconciliation__r.Id = :this.currReconciliation.Id];
        return refunds;
    }*/
    
    private void getRelatedParents() {
        List<Id> relatedFiscalDocuments = new List<Id>();
        List<Id> relatedPayments = new List<Id>();
        List<Id> relatedRefunds = new List<Id>();
        this.ledgerItems = new Map<Id, Decimal>();
        for (Ledger_Item__c item : [SELECT Amount__c, Fiscal_Document__c, Payment__c, Refund__c, Fiscal_Document__r.Recordtype.DeveloperName FROM Ledger_Item__c WHERE Reconciliation__c = :this.currReconciliation.Id]) {
        	system.debug(item);
            if (item.Fiscal_Document__c != null) {
                if(item.Fiscal_Document__r.RecordType.DeveloperName == 'sales_invoice') {
                    this.totalInvoicesAllocated += item.Amount__c;
                } else {
                    this.totalCreditNotesAllocated += item.Amount__c;
                }
                this.ledgerItems.put(item.Fiscal_Document__c, item.Amount__c);
                relatedFiscalDocuments.add(item.Fiscal_Document__c);
            }
            if (item.Payment__c != null) {
                this.totalPaymentsAllocated += item.Amount__c;
                this.ledgerItems.put(item.Payment__c, item.Amount__c);
                relatedPayments.add(item.Payment__c);
            }
            if (item.Refund__c != null) {
                this.totalRefundsAllocated += item.Amount__c;
                this.ledgerItems.put(item.Refund__c, item.Amount__c);
                relatedRefunds.add(item.Refund__c);
            }
        }
        
        system.debug(relatedFiscalDocuments);
        
        if (!relatedFiscalDocuments.isEmpty()) {
            this.salesInvoiceRelations = [SELECT Id, Reference__c, Subtotal__c, Date__c, Status__c FROM Fiscal_Document__c WHERE Id IN :relatedFiscalDocuments AND RecordType.DeveloperName = 'sales_invoice'];
            if (this.salesInvoiceRelations.isEmpty()) {
                this.salesInvoiceRelations = null;
            }
            this.creditNoteRelations = [SELECT Id, Reference__c, Subtotal__c, Date__c, Status__c FROM Fiscal_Document__c WHERE Id IN :relatedFiscalDocuments AND RecordType.DeveloperName = 'credit_note'];
            if (this.creditNoteRelations.isEmpty()) {
                this.creditNoteRelations = null;
            }
        }
        if (!relatedPayments.isEmpty()) {
            this.paymentRelations = [SELECT Id, Reference__c, Amount__c, Date__c, Source__c, Status__c FROM Payment__c WHERE Id IN :relatedPayments];
        }
        if (!relatedRefunds.isEmpty()) {
            this.refundRelations = [SELECT Id, Name, Amount__c, Date__c, Status__c FROM Refund__c WHERE Id IN :relatedRefunds];
        }
    }
    
    /*public void removeSelected() {
        List<Id> fiscalDocuments = new List<Id>();
        List<Id> payments = new List<Id>();
        List<Id> refunds = new List<Id>();
        for(Id key: this.removedDocuments.keySet()) {
            if(this.removedDocuments.get(key) == true) {
                fiscalDocuments.add(key);
            }
        }
        if(fiscalDocuments.size() > 0) {
            LedgerItem.removeReconciliation(fiscalDocuments);
        }
        
        for(Id key: this.removedPayments.keySet()) {
            if(this.removedPayments.get(key) == true) {
                payments.add(key);
            }
        }
        if(payments.size() > 0) {
            LedgerItem.removeReconciliation(payments);
        }
        
        for(Id key: this.removedRefunds.keySet()) {
            if(this.removedRefunds.get(key) == true) {
                refunds.add(key);
            }
        }
        if(refunds.size() > 0) {
            LedgerItem.removeReconciliation(refunds);
        }
    }*/
    
    public PageReference deleteReconciliation() {
        Set<Id> reconciliationIds = new Set<Id>();
        Reconciliation__c tmpRecon = new Reconciliation__c();
        tmpRecon = [SELECT Account__r.Auto_Reconcile__c FROM Reconciliation__c WHERE Id = :this.currReconciliation.Id];
        
        if(tmpRecon.Account__r.Auto_Reconcile__c) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Cannot delete reconciliation for acounts set to reconcile automatically. Please set \'Auto Reconcile\' to disable before deleting reconciliations'));
    		return null;
        }
        reconciliationIds.add(this.currReconciliation.Id);
        Reconciliation.unreconcileReconciliations(reconciliationIds);
        Schema.DescribeSObjectResult result = Reconciliation__c.SObjectType.getDescribe();
		PageReference pageRef = new PageReference('/' + result.getKeyPrefix());
		pageRef.setRedirect(true);
		return pageRef;
    }
    
    /*public PageReference addItem() {
        PageReference pf = new PageReference('/apex/ReconciliationItem');
        pf.getParameters().put('accountId',this.currReconciliation.Account__c);
        pf.getParameters().put('reconciliationId',this.currReconciliation.Id);
        pf.setRedirect(true);
        return pf;
    }*/
}