src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Dispute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>credit_note</fullName>
        <active>true</active>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nominal Code</label>
        <referenceTo>Nominal_Code__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fiscal Document Line</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Document Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Nominal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Nominal Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Match with invoice reference</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountStatementTestClass.cls
@isTest
private class AccountStatementTestClass {

    static testMethod void testAccountStatement() {
    	Pricebook2 testPricebook = new Pricebook2(
    		IsActive = true,
    		Name = 'Standard Pricebook'
    	);
    	insert testPricebook;
    	
    	RecordType salesInvoiceRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'sales_invoice'];
    	
    	Nominal_Code__c testNominalCode = new Nominal_Code__c(
    		Name = '100',
    		Description__c = 'Test Nominal Code'
    	);
    	insert testNominalCode;
        
        Account account = new Account(Name = 'Test', Auto_Reconcile__c = true);
        insert account;
        
        Payment__c payment = new Payment__c(Account__c = account.Id, Amount__c = 25, Draft__c = true, Confirmed__c = false, Failed__c = false, Description__c = 'Test');
        insert payment;
        payment.Draft__c = false;
        payment.Confirmed__c = true;
        update payment;
        
        Fiscal_Document__c fd = new Fiscal_Document__c(Account__c = account.Id, Description__c = 'Test Different', Draft__c = true, Dispute__c = true, Price_Book__c = testPricebook.Id, RecordTypeId = salesInvoiceRecordType.Id);
        
        insert fd;

        Fiscal_Document_Line__c fdl = new Fiscal_Document_Line__c(Fiscal_Document__c = fd.Id, Description__c = 'Test', Nominal_Code__c = testNominalCode.Id, Quantity__c = 1, Amount__c = 25);
        insert fdl;
        
        fd.Draft__c = false;
        update fd;
        
        AccountStatement acctStatement;
        
        acctStatement = new AccountStatement();
        system.assertEquals(1, ApexPages.getMessages().size());
        system.assertEquals('Account ID not Specified', ApexPages.getMessages()[0].getDetail());
        
        ApexPages.currentPage().getParameters().put('accountid', account.Id);
        acctStatement = new AccountStatement();
        
        system.assertEquals(2, ApexPages.getMessages().size());
        system.assertEquals('There are Disputed Invoices on the Account', ApexPages.getMessages()[1].getDetail());
        
        acctStatement.startDate = Date.today();
        acctStatement.endDate = Date.today().addDays(-30);
        acctStatement.initStatement();
        
        system.assertEquals(3, ApexPages.getMessages().size());
        system.assertEquals('From date cannot be greater than To date', ApexPages.getMessages()[2].getDetail());
        
        acctStatement.startDate = Date.today();
        acctStatement.endDate = Date.today().addDays(30);
        acctStatement.initStatement();
        
        system.assertEquals(4, ApexPages.getMessages().size());
        system.assertEquals('From/To Dates cannot be in future', ApexPages.getMessages()[3].getDetail());
        
        system.assertEquals(0, acctStatement.getInitialBalance());
        system.assertEquals(0, acctStatement.getLastBalance());
        system.assertEquals(0, acctStatement.getOpeningDebit());
        system.assertEquals(0, acctStatement.getOpeningCredit());
		system.assertEquals(25, acctStatement.getClosingDebit());
        system.assertEquals(25, acctStatement.getClosingCredit());
        
        system.assertEquals('/apex/ManualReconcileCreditItem', acctStatement.manualReconcile().getUrl().split('\\?')[0]);
        system.assertEquals('/apex/PaymentTake', acctStatement.takePayment().getUrl().split('\\?')[0]);
        system.assertEquals('/apex/PaymentTake', acctStatement.takeOutstandingPayment().getUrl().split('\\?')[0]);
    }
    
    static testMethod void testAccountStatement2() {
    	Pricebook2 testPricebook = new Pricebook2(
    		IsActive = true,
    		Name = 'Standard Pricebook'
    	);
    	insert testPricebook;
    	
    	RecordType salesInvoiceRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'sales_invoice'];
    	
    	Nominal_Code__c testNominalCode = new Nominal_Code__c(
    		Name = '100',
    		Description__c = 'Test Nominal Code'
    	);
    	insert testNominalCode;
    	
        Account account = new Account(Name = 'Test', Auto_Reconcile__c = true);
        insert account;
        
        Fiscal_Document__c fd = new Fiscal_Document__c(Account__c = account.Id, Description__c = 'Test Different', Draft__c = true, Dispute__c = false, Price_Book__c = testPricebook.Id, RecordTypeId = salesInvoiceRecordType.Id, Date__c = Date.today().addDays(-30));
        insert fd;

        Fiscal_Document_Line__c fdl = new Fiscal_Document_Line__c(Fiscal_Document__c = fd.Id, Description__c = 'Test', Nominal_Code__c = testNominalCode.Id, Quantity__c = 1, Amount__c = 25);
        insert fdl;
        
        fd.Draft__c = false;
        update fd;
        
        ApexPages.currentPage().getParameters().put('accountid', account.Id);
		AccountStatement acctStatement = new AccountStatement();
        
        acctStatement.initStatementOutstandingOnly();
        
        acctStatement.startDate = Date.today();
        acctStatement.endDate = Date.today().addDays(-30);
        acctStatement.initStatementOutstandingOnly();
        
        system.assertEquals(1, ApexPages.getMessages().size());
        system.assertEquals('From date cannot be greater than To date', ApexPages.getMessages()[0].getDetail());
        
        acctStatement.startDate = Date.today();
        acctStatement.endDate = Date.today().addDays(30);
        acctStatement.initStatementOutstandingOnly();
        
        system.assertEquals(2, ApexPages.getMessages().size());
        system.assertEquals('From/To Dates cannot be in future', ApexPages.getMessages()[1].getDetail());
    }
    
    static testMethod void testAccountStatement3() {
    	Pricebook2 testPricebook = new Pricebook2(
    		IsActive = true,
    		Name = 'Standard Pricebook'
    	);
    	insert testPricebook;
    	
    	RecordType creditNoteRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'credit_note'];
    	
    	Nominal_Code__c testNominalCode = new Nominal_Code__c(
    		Name = '100',
    		Description__c = 'Test Nominal Code'
    	);
    	insert testNominalCode;
    	
        Account account = new Account(Name = 'Test', Auto_Reconcile__c = true);
        insert account;
        
        Fiscal_Document__c fd = new Fiscal_Document__c(Account__c = account.Id, Description__c = 'Test Different', Draft__c = true, Dispute__c = false, Price_Book__c = testPricebook.Id, RecordTypeId = creditNoteRecordType.Id);
        insert fd;

        Fiscal_Document_Line__c fdl = new Fiscal_Document_Line__c(Fiscal_Document__c = fd.Id, Description__c = 'Test', Nominal_Code__c = testNominalCode.Id, Quantity__c = 1, Amount__c = 10);
        insert fdl;
        
        fd.Draft__c = false;
        update fd;
        
        Payment__c payment = new Payment__c(Account__c = account.Id, Amount__c = 25, Draft__c = true, Confirmed__c = false, Failed__c = false, Description__c = 'Test');
        insert payment;
        payment.Draft__c = false;
        payment.Confirmed__c = true;
        update payment;
        
        Refund__c refund = new Refund__c(Payment__c = payment.Id, Amount__c = 10, Draft__c = false);
        insert refund;
        
        ApexPages.currentPage().getParameters().put('accountid', account.Id);
		AccountStatement acctStatement = new AccountStatement();
        
        acctStatement.initStatement();
    }
        
        //--------------------------------------------------
        
        
	static testMethod void testAccountStatement4() {
        Pricebook2 testPricebook = new Pricebook2(
    		IsActive = true,
    		Name = 'Standard Pricebook'
    	);
    	insert testPricebook;
    	
    	RecordType creditNoteRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'credit_note'];
    	
    	Nominal_Code__c testNominalCode = new Nominal_Code__c(
    		Name = '100',
    		Description__c = 'Test Nominal Code'
    	);
    	insert testNominalCode;
        Account account = new Account(Name = 'Test', Auto_Reconcile__c = true);
        insert account;
        AccountStatement acctStatement = new AccountStatement();
        acctStatement.accountId = account.Id;
        acctStatement.account = account;
        
        acctStatement.initStatement();
        
        Fiscal_Document__c fd = new Fiscal_Document__c(Account__c = account.Id, Description__c = 'Test Different', Draft__c = true, Dispute__c = false, Price_Book__c = testPricebook.Id, RecordTypeId = creditNoteRecordType.Id);
        insert fd;

        Fiscal_Document_Line__c fdl = new Fiscal_Document_Line__c(Fiscal_Document__c = fd.Id, Description__c = 'Test', Nominal_Code__c = testNominalCode.Id, Quantity__c = 1, Amount__c = 10);
        insert fdl;
        
        fd.Draft__c = false;
        update fd;
        
        Contact contact = new Contact(FirstName = 'test', LastName = 'email', Email = 'test@test.com', AccountId = account.Id);
        insert contact;
        acctStatement.sendEmail();
        
        PageReference pg;
        pg = acctStatement.viewPdf();
        system.assertEquals(pg.getUrl(), '/apex/AccountStatementPDF?accountId=' + String.valueOf(account.Id) + '&enddate=' + String.valueOf(acctStatement.endDate) + '&startdate=' + String.valueOf(acctStatement.startDate) + '&unallocatedonly=' + String.valueOf(acctStatement.outstandingOnly));
        
        system.assertEquals(acctStatement.getOddRowColour(), 'white',' here 1');
        system.assertEquals(acctStatement.getEvenRowColour(), '#f7f7f9',' here 2');
        
        system.assertEquals(acctStatement.getTextColour(), '#00bb00',' here 3');
        system.assertEquals(acctStatement.getLogo(), PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl(),' here 4');
        system.assertEquals(acctStatement.getFooterImage(), PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl(),' here 5');
        system.assertEquals(acctStatement.getWebsite(), 'smartcities.connexin.co.uk',' here 6');
        
        account.Type = 'Residential';
        acctStatement.account = account;
        system.assertEquals(acctStatement.getTextColour(), '#ec1c24',' here 7');
        system.assertEquals(acctStatement.getLogo(), PageReference.forResource('Connexin_Home_Logo').getUrl(),' here 8');
        system.assertEquals(acctStatement.getFooterImage(), PageReference.forResource('Connexin_Home_Footer').getUrl(),' here 9');
        system.assertEquals(acctStatement.getWebsite(), 'home.connexin.co.uk',' here 10');
        
        account.Type = 'Business';
        acctStatement.account = account;
        system.assertEquals(acctStatement.getTextColour(), '#00aff0',' here 11');
        system.assertEquals(acctStatement.getLogo(), PageReference.forResource('Connexin_Business_Logo').getUrl(),' here 12');
        system.assertEquals(acctStatement.getFooterImage(), PageReference.forResource('Connexin_Business_Footer').getUrl(),' here 13');
        system.assertEquals(acctStatement.getWebsite(), 'business.connexin.co.uk',' here 14');
        
        account.Type = 'Public Sector';
        acctStatement.account = account;
        system.assertEquals(acctStatement.getTextColour(), '#00bb00',' here 15');
        system.assertEquals(acctStatement.getLogo(), PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl(),' here 16');
        system.assertEquals(acctStatement.getFooterImage(), PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl(),' here 17');
        system.assertEquals(acctStatement.getWebsite(), 'smartcities.connexin.co.uk',' here 18');     
        
    }
}