src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Match with invoice reference</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Manual&quot;</defaultValue>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>go_cardless</fullName>
                </value>
                <value>
                    <fullName>stripe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentTestClass.cls
@isTest
private class PaymentTestClass {
	
    static testMethod void testPaymentReferenceTrigger() {
    	
        Account account = new Account(Name = 'Test Account', Auto_Reconcile__c = true);
        insert account;
    	
    	Payment__c payment1 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 1, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment1;
		
    	Payment__c payment2 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 2, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment2;
		
    	Payment__c payment3 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 3, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment3;
		
    	Payment__c payment4 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 4, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment4;
		
    	Payment__c payment5 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 5, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment5;
		
    	Payment__c payment6 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 6, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment6;
		
    	Payment__c payment7 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 7, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment7;
		
    	Payment__c payment8 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 8, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment8;
		
    	Payment__c payment9 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 9, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment9;
		
    	Payment__c payment10 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 10, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment10;
		
    	Payment__c payment11 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 11, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment11;
		
    	Payment__c payment12 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Date__c = Date.newInstance(2018, 12, 1),
    		Draft__c = true,
    		Confirmed__c = false,
    		Failed__c = false,
    		Description__c = 'Test'
		);
		insert payment12;
		
		Payment__c payment13 = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 25,
    		Source__c = 'go_cardless'
		);
		try {
			insert payment13;
			system.assert(false);
        } catch (DMLException e) {
        	
        }
    }
    
    static testMethod void testpaymentLedgerItemUpdateAndPaymentDeletionValidationTrigger() {
        Account account = new Account(Name = 'Test Account', Auto_Reconcile__c = true);
        insert account;
        
    	Payment__c payment = new Payment__c(
    		Account__c = account.Id,
    		Amount__c = 10,
    		Draft__c = false,
    		Confirmed__c = true,
    		Failed__c = false,
    		Reference__c = 'Test',
    		Source__c = 'go_cardless',
    		Description__c = 'Test'
    	);
    	insert payment;
    	
        try {
        	delete payment;
        	system.assert(false);
        } catch (DMLException e) {
        	
        }
    	
    }
}