src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Auto_Reconcile__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Uncheck for Manual Reconciliation</description>
        <inlineHelpText>Uncheck for Manual Reconciliation</inlineHelpText>
        <label>Auto Reconcile</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Dispute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Total</label>
        <summarizedField>Fiscal_Document_Line__c.Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nominal Code</label>
        <referenceTo>Nominal_Code__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <formula>Amount__c * (1 + Tax_Rate__c) * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tax</label>
        <referenceTo>Tax__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fiscal Document Line</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Document Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Nominal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Nominal Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Match with invoice reference</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Manual&quot;</defaultValue>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>go_cardless</fullName>
                </value>
                <value>
                    <fullName>stripe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nominal Code</label>
        <referenceTo>Nominal_Code__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FiscalDocumentsControllerTestClass.cls
@isTest
private class FiscalDocumentsControllerTestClass {

    static testMethod void testStandardController() {
    	Pricebook2 testPricebook = new Pricebook2(
    		IsActive = true,
    		Name = 'Standard Pricebook'
    	);
    	insert testPricebook;
    	
    	RecordType salesInvoiceRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'sales_invoice'];
    	
    	Tax__c testTax = new Tax__c(
    		Name = 'Test Tax',
    		Rate__c = 20
    	);
    	insert testTax;
    	
    	Nominal_Code__c testNominalCode = new Nominal_Code__c(
    		Name = '100',
    		Description__c = 'Test Nominal Code'
    	);
    	insert testNominalCode;
    	
    	Product2 testProduct = new Product2(
    		Name = 'Test Product',
    		ProductCode = 'Test',
    		Description = 'Test Product',
    		Nominal_Code__c = testNominalCode.Id
    	);
    	
        Account account = new Account(Name = 'Test Account', Auto_Reconcile__c = true);
        insert account;
        
        Fiscal_Document__c fd = new Fiscal_Document__c(Account__c = account.Id, Description__c = 'Test Different', Draft__c = true, Dispute__c = false, Price_Book__c = testPricebook.Id, RecordTypeId = salesInvoiceRecordType.Id);
        insert fd;
        
        fd = [SELECT Id, Name, Account__c, Description__c, Draft__c, Dispute__c, Price_Book__c, Subtotal__c, Amount_Allocated__c, Reference__c, Sent__c FROM Fiscal_Document__c WHERE Id = :fd.Id];
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(fd);
        FiscalDocumentsController controller = new FiscalDocumentsController(stdController);
        
        PageReference pg;
		pg = controller.validateDraft();
		system.assertEquals(pg, null);
		
        Fiscal_Document_Line__c fdl = new Fiscal_Document_Line__c(Fiscal_Document__c = fd.Id, Description__c = 'Test', Tax__c = testTax.Id, Nominal_Code__c = testNominalCode.Id, Product__c = testProduct.Id, Quantity__c = 1, Amount__c = 20.83);
        insert fdl;
		
		pg = controller.validateDraft();
        system.assertEquals(pg.getUrl(), '/apex/FiscalDocumentActionsConfirmation?id=' + String.valueOf(fd.Id));
        
        pg = controller.takePayment();
        system.assertEquals(pg.getUrl(), '/apex/PaymentTake?account=' + fd.Account__c + '&amount=' + String.valueOf(fd.Subtotal__c - fd.Amount_Allocated__c) + '&description=' + EncodingUtil.urlEncode(fd.Reference__c, 'UTF-8') + '&documentid=' + fd.Id);
        
        pg = controller.viewPdf();
        system.assertEquals(pg.getUrl(), '/apex/FiscalDocumentPDF?id=' + String.valueOf(fd.Id));
        
        controller.sendEmail();
        
        Contact contact = new Contact(FirstName = 'test', LastName = 'email', Email = 'test@test.com', AccountId = account.Id);
        insert contact;
        controller.sendEmail();
        fd = [SELECT Id, Name, Account__c, Description__c, Draft__c, Dispute__c, Price_Book__c, Subtotal__c, Amount_Allocated__c, Reference__c, Sent__c FROM Fiscal_Document__c WHERE Id = :fd.Id];
        system.assertEquals(fd.Sent__c, true);
        
        Payment__c payment = new Payment__c(Account__c = account.Id, Amount__c = 25, Draft__c = false, Confirmed__c = true, Failed__c = false, Description__c = 'Test', Source__c = 'go_cardless', Reference__c = 'test');
        insert payment;
        
        controller.getLinkedLedgerItems();
        
        system.assertEquals(controller.getOddRowColour(), 'white');
        system.assertEquals(controller.getEvenRowColour(), '#f7f7f9');
        
        system.assertEquals(controller.getTextColour(), '#00bb00');
        system.assertEquals(controller.getLogo(), PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl());
        system.assertEquals(controller.getFooterImage(), PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl());
        system.assertEquals(controller.getWebsite(), 'smartcities.connexin.co.uk');
        
        account.Type = 'Residential';
        controller.account = account;
        system.assertEquals(controller.getTextColour(), '#ec1c24');
        system.assertEquals(controller.getLogo(), PageReference.forResource('Connexin_Home_Logo').getUrl());
        system.assertEquals(controller.getFooterImage(), PageReference.forResource('Connexin_Home_Footer').getUrl());
        system.assertEquals(controller.getWebsite(), 'home.connexin.co.uk');
        
        account.Type = 'Business';
        controller.account = account;
        system.assertEquals(controller.getTextColour(), '#00aff0');
        system.assertEquals(controller.getLogo(), PageReference.forResource('Connexin_Business_Logo').getUrl());
        system.assertEquals(controller.getFooterImage(), PageReference.forResource('Connexin_Business_Footer').getUrl());
        system.assertEquals(controller.getWebsite(), 'business.connexin.co.uk');
        
        account.Type = 'Public Sector';
        controller.account = account;
        system.assertEquals(controller.getTextColour(), '#00bb00');
        system.assertEquals(controller.getLogo(), PageReference.forResource('Connexin_Smart_Cities_Logo').getUrl());
        system.assertEquals(controller.getFooterImage(), PageReference.forResource('Connexin_Smart_Cities_Footer').getUrl());
        system.assertEquals(controller.getWebsite(), 'smartcities.connexin.co.uk');
        
        pg = controller.cloneFiscalDocumentToCreditNote();
    }
}