src/objects/Default_Tax__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Default Tax</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Default Tax</label>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Subtotal__c</fullName>
        <label>Subtotal</label>
        <summarizedField>Fiscal_Document_Line__c.Net_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Total</label>
        <summarizedField>Fiscal_Document_Line__c.Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Tax_Subtotal__c</fullName>
        <label>Tax</label>
        <summarizedField>Fiscal_Document_Line__c.Tax_Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Subtotal__c</fullName>
        <formula>Subtotal__c - Tax_Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Nominal Code</label>
        <referenceTo>Nominal_Code__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <formula>Amount__c * (1 + Tax_Rate__c) * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tax_Subtotal__c</fullName>
        <formula>Amount__c * Tax_Rate__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tax</label>
        <referenceTo>Tax__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fiscal Document Line</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Document Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Nominal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Nominal Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nominal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Tax__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax</label>
        <referenceTo>Tax__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Price_Book_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Nominal_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nominal Code</label>
        <referenceTo>Nominal_Code__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FiscalDocumentLineController.cls
public class FiscalDocumentLineController {
    private ApexPages.StandardController stdController;
    public Fiscal_Document_Line__c fiscal_document_line {get; set;}
    public Decimal subtotal {get; set;}
    public Decimal tax_subtotal {get; set;}
    public Decimal net_subtotal {get; set;}
    public Id pricebook {get; set;}
    
    public FiscalDocumentLineController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.fiscal_document_line = (Fiscal_Document_Line__c)this.stdController.getRecord();
        if (this.fiscal_document_line.Id != null) {
            this.fiscal_document_line = [SELECT Id, Fiscal_Document__c, Product__c, Description__c, Amount__c, Quantity__c, Nominal_Code__C, Tax__c, Net_Subtotal__c, Tax_Subtotal__c, Subtotal__c FROM Fiscal_Document_Line__c WHERE Id = :this.fiscal_document_line.Id];
        }
        
        if (Default_Tax__c.getValues('default') != null) {
            this.fiscal_document_line.Tax__c = Default_Tax__c.getValues('default').Tax__c;
        }
        
        this.subtotal = this.fiscal_document_line.Subtotal__c;
        this.tax_subtotal = this.fiscal_document_line.Tax_Subtotal__c;
        this.net_subtotal = this.fiscal_document_line.Net_Subtotal__c;
        
        if (this.pricebook == null) {
            Fiscal_Document__c fiscalDocument = [SELECT Id, Price_Book__c FROM Fiscal_Document__c WHERE Id = :this.fiscal_document_line.Fiscal_Document__c];
            this.pricebook =  fiscalDocument.Price_Book__c;
        }
    }
    
    public PageReference save() {
        try {
            if (this.fiscal_document_line.Id == null) {
                insert this.fiscal_document_line;
            } else {
                update this.fiscal_document_line;
            }
        } catch (Exception e) { 
            ApexPages.addMessages(e);
            return null;
        }
        
        return this.stdController.save();
    }
    
    public void selectProduct() {
        Pricebook2 selPricebook;
        Set<Id> pricebookIds = new Set<Id>();
        for (Pricebook2 pricebook : [SELECT Id, IsStandard FROM Pricebook2 WHERE IsStandard = true OR Id = :this.pricebook]) {
            pricebookIds.add(pricebook.Id);
            if (pricebook.IsStandard == false) {
                selPricebook = pricebook;
            }
        }
        
        Product2 product = [SELECT Id, Description, Nominal_Code__c FROM Product2 WHERE Id = :this.fiscal_document_line.Product__c];
        this.fiscal_document_line.Description__c = product.Description;
        
        for (PricebookEntry pricebookentry : [SELECT Id, UnitPrice, Pricebook2Id FROM PricebookEntry WHERE Product2Id = :product.Id AND Pricebook2Id IN :pricebookIds]) {
            //If we're using the standard pricebook
            if (selPricebook == null) {
                this.fiscal_document_line.Amount__c = pricebookentry.UnitPrice;
                //If we've specified a pricebook
            } else if (pricebookentry.Pricebook2Id == selPricebook.Id) {
                this.fiscal_document_line.Amount__c = pricebookentry.UnitPrice;
                //If we've specified a pricebook but there is no pricebook entry for the selected product
            } else if (selPricebook != null) {
                this.fiscal_document_line.Amount__c = pricebookentry.UnitPrice;
            }
        }
        
        this.fiscal_document_line.Nominal_Code__c = product.Nominal_Code__c;
        
        this.calculateSubtotals();
    }
    
    public void calculateSubtotals() {
        if (this.fiscal_document_line.Tax__c == null) {
            this.fiscal_document_line.Tax_Rate__c = 0;
        } else {
            Tax__c tax = [SELECT Id, Rate__c FROM Tax__c WHERE Id = :this.fiscal_document_line.Tax__c];
            this.fiscal_document_line.Tax_Rate__c = tax.Rate__c;
        }
        
        this.subtotal = this.fiscal_document_line.Amount__c * (1 + this.fiscal_document_line.Tax_Rate__c / 100) * this.fiscal_document_line.Quantity__c;
        this.tax_subtotal = this.fiscal_document_line.Amount__c * this.fiscal_document_line.Tax_Rate__c / 100 * this.fiscal_document_line.Quantity__c;
        this.net_subtotal = this.subtotal - this.tax_subtotal;
    }
    
}