src/objects/Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Direct Debits</relationshipLabel>
        <relationshipName>Direct_Debits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Direct Debit</label>
    <nameField>
        <label>Go Cardless ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Direct Debits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Proc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Dispute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(RecordType.DeveloperName == &apos;sales_invoice&apos;,
    IF(Amount_Allocated__c == Subtotal__c, &apos;Paid&apos;,
      IF(Amount_Allocated__c == 0, &apos;Open&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Paid&apos;, &apos;&apos;)
      )
      &amp;
      IF( Due_Date__c &lt; DATEVALUE(NOW()), IF( Actual_Due_Date__c &gt;= DATEVALUE(NOW()), &apos; - Overdue (Buffer)&apos;, &apos; - Overdue&apos;), &apos;&apos;)
    ),
    IF(Amount_Allocated__c == Subtotal__c, &apos;Allocated&apos;,
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c &lt; Subtotal__c, &apos;Partially Allocated&apos;, &apos;&apos;)
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Total</label>
        <summarizedField>Fiscal_Document_Line__c.Subtotal_Value__c</summarizedField>
        <summaryForeignKey>Fiscal_Document_Line__c.Fiscal_Document__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>credit_note</fullName>
        <active>true</active>
        <label>Credit Note</label>
    </recordTypes>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>IF(
  NOT(ISNULL(Fiscal_Document__r.Date__c)),
  Fiscal_Document__r.Date__c,
  IF(
    NOT(ISNULL(Payment__r.Date__c)),
    Payment__r.Date__c,
    IF(
      NOT(ISNULL(Refund__r.Date__c)),
      Refund__r.Date__c,
      null
    )
  )
)</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>Reconciliation__r.Reconciled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;, IF(Reconciled__c == True, &apos;Allocated&apos;, &apos;Unallocated&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <recordTypes>
        <fullName>credit</fullName>
        <active>true</active>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>debit</fullName>
        <active>true</active>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Date__c</fullName>
        <label>Charge Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Match with invoice reference</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <defaultValue>&quot;Manual&quot;</defaultValue>
        <label>Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>manual</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>go_cardless</fullName>
                </value>
                <value>
                    <fullName>stripe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
  IF(Failed__c == True, &apos;Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Paid - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliations</relationshipLabel>
        <relationshipName>Reconciliations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Credits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Debits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Refund Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(Draft__c == True, &apos;Draft&apos;,
IF(Failed__c == True, &apos;Failed&apos;,
  IF(Payment_Failed__c == True, &apos;Payment Failed&apos;,
    IF(Confirmed__c == False, &apos;Pending&apos;,
      &apos;Confirmed - &apos;
      &amp;
      IF(Amount_Allocated__c == 0, &apos;Unallocated&apos;,
        IF(Amount_Allocated__c == Amount__c, &apos;Allocated&apos;,
          IF(Amount_Allocated__c &lt; Amount__c, &apos;Partially Allocated&apos;, &apos;&apos;)
        )
      )
    )
  )
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentController.cls
public class PaymentController {
    public Payment__c payment {get;set;}
    private ApexPages.StandardController stdController;
    
    public List<Reconciliation__c> reconciliationRelations {get;set;}
    public List<Fiscal_Document__c> salesInvoiceRelations {get;set;}
    public List<Fiscal_Document__c> creditNoteRelations {get;set;}
    public List<Payment__c> paymentRelations {get;set;}
    public List<Refund__c> refundRelations {get;set;}
    
    public Decimal totalInvoicesAllocated {get; set;}
    public Decimal totalCreditNotesAllocated {get; set;}
    public Decimal totalPaymentsAllocated {get; set;}
    public Decimal totalRefundsAllocated {get; set;}
    
    public Id documentId {get; set;}
    
    public Map<Id, Decimal> ledgerItems {get;set;}
    
    public String stripeToken {get;set;}
    public Boolean locked {get;set;}
    
    private Direct_Debit__c directDebit;
        
    public PaymentController(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.payment = (Payment__c)this.stdController.getRecord();
        this.totalInvoicesAllocated = 0.00;
        this.totalCreditNotesAllocated = 0.00;
        this.totalPaymentsAllocated = 0.00;
        this.totalRefundsAllocated = 0.00;
        
        if (this.payment.Id != null) {
            this.getRelatedParents();
        }
    }
    
    public PaymentController(ApexPages.StandardSetController controller) {
        this.payment = new Payment__c();
        this.locked = false;
        this.payment.Source__c = '';
        if (System.currentPageReference().getParameters().get('amount') != null) {
            this.payment.Amount__c = Decimal.valueOf(System.currentPageReference().getParameters().get('amount'));
        }
        if (System.currentPageReference().getParameters().get('account') != null) {
            this.payment.Account__c = System.currentPageReference().getParameters().get('account');
            this.accountUpdated();
            
            Payment__c[] payments = [SELECT Id FROM Payment__c WHERE Draft__c = false AND Failed__c = false AND Confirmed__c = false AND Account__c = :this.payment.Account__c];
            if (payments.size() > 0) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'There are Pending Payments on the Account - are you sure you want to proceed?'));
            }
        }
        if (System.currentPageReference().getParameters().get('description') != null) {
            this.payment.Description__c = System.currentPageReference().getParameters().get('description');
        }
        if (System.currentPageReference().getParameters().get('amount') != null && System.currentPageReference().getParameters().get('account') != null && System.currentPageReference().getParameters().get('description') != null) {
            this.locked = true;
        }
        if (System.currentPageReference().getParameters().get('documentid') != null) {
            this.documentId = System.currentPageReference().getParameters().get('documentid');
            
            Fiscal_Document__c fiscalDocument = [SELECT Id, Auto_Proc__c, Dispute__c FROM Fiscal_Document__c WHERE Id = :this.documentId AND Draft__C = false];
            if (fiscalDocument.Auto_Proc__c == true) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Invoice has been Auto Processed - are you sure you want to proceed?'));
            }
            if (fiscalDocument.Dispute__c == true) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Invoice is in Dispute - are you sure you want to proceed?'));
            }
        }
        
        
        
    }
    
    public PageReference validateDraft() {
        this.payment.Draft__c = false;
        this.payment.Confirmed__c = true;
        
        try {
            update this.payment;
        } catch (Exception e) { 
            ApexPages.addMessages(e);
            return null;
        }
        
        return this.stdController.view();
    }
    
    public PageReference takePayment() {
        if (this.payment.Source__c == 'stripe') {
            StripeCharge charge = StripeAPI.createCharge(Integer.valueOf(this.payment.Amount__c * 100), this.stripeToken, this.payment.Description__c);
            if (charge.error) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,charge.error_desc));
                return null;
            }
            
            //Add Error Handling Code
            if (this.payment.Amount__c * 100 != charge.amount) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Invalid Payment Amount'));
                return null;
            }
            
            payment.Reference__c = charge.Id;
            payment.Confirmed__c = true;
            
        } else if (this.payment.Source__c == 'go_cardless') {
            if (this.payment.Amount__c < 1) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Cannot take a Direct Debit for less than £1'));
                return null;
            }
            
            GoCardlessPayment goCardlessPayment = GoCardlessAPI.createCustomerPayment(this.directDebit.Name, Integer.valueOf(this.payment.Amount__c * 100), this.payment.Description__c, null);
            
            //Add Error Handling Code
            if (goCardlessPayment == null) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Go Cardless Request Failed'));
                return null;
            }
            
            if (goCardlessPayment.amount != this.payment.Amount__c * 100) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Go Cardless Request Failed'));
                return null;
            }
            
            payment.Reference__c = goCardlessPayment.id;
            payment.Confirmed__c = false;
            payment.Charge_Date__c = goCardlessPayment.charge_date;
            
        } else { //Not a Stripe or Go Cardless Payment so Don't Insert Anything
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Invalid API'));
            return null;
        }
        
        //Prepare to Insert the Newly Created Payment
        payment.Draft__c = false;
        
        try {
            insert payment;
        } catch (Exception e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        if (this.documentId != null) {
            Fiscal_Document__c invoice = new Fiscal_Document__c(
                Id = this.documentId,
                Auto_Proc__c = true
            );
            
            try {
                update invoice;
            } catch (Exception e) {
                ApexPages.addMessages(e);
                return null;
            }
        }
        
        //Redirect the User to the Newly Created Payment
        PageReference pg = new ApexPages.StandardController(payment).view();
        pg.setRedirect(true);
        return pg;
    }
    
    public void accountUpdated () {
        this.payment.Source__c = 'stripe';
        List<Direct_Debit__c> directDebitList = [SELECT Id, Name FROM Direct_Debit__c WHERE Account__c = :this.payment.Account__c];
        if (directDebitList.isEmpty()) {
            this.directDebit = null;
        } else {
            this.directDebit = directDebitList.get(0);
            this.payment.Source__c = 'go_cardless';
        }
    }
    
    //Limit the User's Source Selection to just Available Payment Gateways
    public List<SelectOption> getPaymentGatewayList() {
        List<SelectOption> options = new List<SelectOption>();
        if (this.payment.Account__c == null) {
            options.add(new SelectOption('', ''));
        } else {
            if (this.directDebit != null) {
                options.add(new SelectOption('go_cardless', 'Direct Debit'));
            }
            options.add(new SelectOption('stripe', 'Credit/Debit Card'));
        }
        return options;
    }
    
    private void getRelatedParents() {
        List<Id> relatedReconciliations = new List<Id>();
        this.ledgerItems = new Map<Id, Decimal>();
        for (Ledger_Item__c item : [SELECT Id, Reconciled__c, Reconciliation__c FROM Ledger_Item__c WHERE Payment__c = :this.payment.Id]) {
            if (item.Reconciled__c == true) {
                relatedReconciliations.add(item.Reconciliation__c);
            }
        }
        
        if (relatedReconciliations.isEmpty()) {
            return;
        }
        
        List<Id> relatedFiscalDocuments = new List<Id>();
        List<Id> relatedPayments = new List<Id>();
        List<Id> relatedRefunds = new List<Id>();
        for (Ledger_Item__c item : [SELECT Amount__c, Fiscal_Document__c, Payment__c, Refund__c, Fiscal_Document__r.RecordType.DeveloperName FROM Ledger_Item__c WHERE Reconciliation__c IN :relatedReconciliations]) {
            if (item.Fiscal_Document__c != null) {
                if (item.Fiscal_Document__r.RecordType.DeveloperName == 'sales_invoice') {
                    this.totalInvoicesAllocated += item.Amount__c;
                } else if (item.Fiscal_Document__r.RecordType.DeveloperName == 'credit_note') {
                    this.totalCreditNotesAllocated += item.Amount__c;
                }
                if (this.ledgerItems.containsKey(item.Fiscal_Document__c)) {
                    this.ledgerItems.put(item.Fiscal_Document__c, this.ledgerItems.get(item.Fiscal_Document__c) + item.Amount__c);
                } else {
                    this.ledgerItems.put(item.Fiscal_Document__c, item.Amount__c);
                }
                relatedFiscalDocuments.add(item.Fiscal_Document__c);
            }
            if (item.Payment__c != null) {
                this.totalPaymentsAllocated += item.Amount__c;
                if (this.ledgerItems.containsKey(item.Payment__c)) {
                    this.ledgerItems.put(item.Payment__c, this.ledgerItems.get(item.Payment__c) + item.Amount__c);
                } else {
                    this.ledgerItems.put(item.Payment__c, item.Amount__c);
                }
                relatedPayments.add(item.Payment__c);
            }
            if (item.Refund__c != null) {
                this.totalRefundsAllocated += item.Amount__c;
                if (this.ledgerItems.containsKey(item.Refund__c)) {
                    this.ledgerItems.put(item.Refund__c, this.ledgerItems.get(item.Refund__c) + item.Amount__c);
                } else {
                    this.ledgerItems.put(item.Refund__c, item.Amount__c);
                }
                relatedRefunds.add(item.Refund__c);
            }
        }
        
        if (!relatedReconciliations.isEmpty()) {
            this.reconciliationRelations = [SELECT Id, Name, Credits__c, Debits__c, Reconciled__c FROM Reconciliation__c WHERE Id IN :relatedReconciliations];
        }
        if (!relatedFiscalDocuments.isEmpty()) {
            this.salesInvoiceRelations = [SELECT Id, Reference__c, Description__c, Subtotal__c, Date__c, Status__c FROM Fiscal_Document__c WHERE Id IN :relatedFiscalDocuments AND RecordType.DeveloperName = 'sales_invoice'];
            if (this.salesInvoiceRelations.isEmpty()) {
                this.salesInvoiceRelations = null;
            }
            this.creditNoteRelations = [SELECT Id, Reference__c, Description__c, Subtotal__c, Date__c, Status__c FROM Fiscal_Document__c WHERE Id IN :relatedFiscalDocuments AND RecordType.DeveloperName = 'credit_note'];
            if (this.creditNoteRelations.isEmpty()) {
                this.creditNoteRelations = null;
            }
        }
        if (!relatedPayments.isEmpty()) {
            this.paymentRelations = [SELECT Id, Reference__c, Amount__c, Date__c, Source__c, Status__c FROM Payment__c WHERE Id IN :relatedPayments];
        }
        if (!relatedRefunds.isEmpty()) {
            this.refundRelations = [SELECT Id, Name, Amount__c, Date__c, Status__c FROM Refund__c WHERE Id IN :relatedRefunds];
        }
    }
    
    public PageReference cancelPayment() {
        PageReference pg;
        if (this.documentId == null) {
            pg = new PageReference('/apex/AccountStatement?accountId=' + this.payment.Account__c);
        } else {
            pg = new PageReference('/apex/FiscalDocumentView?id=' + this.documentId);
        }
        pg.setRedirect(true);
        return pg;
    }
    
    public String getStripePublicAPIKey() {
        return StripeAPI.getPublicAPIKey();
    }
    
}