src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>Reconciliation__r.Reconciled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reconciliation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reconciliation</label>
        <referenceTo>Reconciliation__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <recordTypes>
        <fullName>credit</fullName>
        <active>true</active>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>debit</fullName>
        <active>true</active>
        <label>Debit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reconciliation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reconciliations</relationshipLabel>
        <relationshipName>Reconciliations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Credits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Debits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <label>Reconciliation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Reconciliation.cls
public class Reconciliation {
    
    /*public static Map<Id, Map<String, Decimal>> calculateBalance(Set<Id> reconciliationIds) {
        //Create Map for Return Value
        Map<Id, Map<String, Decimal>> balance = new Map<Id, Map<String, Decimal>>();
        for (Id reconciliationId : reconciliationIds) {
            //Check the IDs are Valid
            if (reconciliationId.getSObjectType().getDescribe().getName() != 'Reconciliation__c') {
                //throw new Exception('ID is not a valid Reconciliation__c ID');
            }
            //Create a balance for the Reconciliation
            balance.put(reconciliationId, new Map<String, Decimal>{'credits' => 0, 'debits' => 0});
        }
        
        //Create Record Type Mapp
        Map<Id, String> recordTypeMap = new Map<Id, String>();
        for (RecordType record : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Ledger_Item__c']) {
            recordTypeMap.put(record.Id, record.DeveloperName);
        }
        
        Map<String, Decimal> curBalance;
        //Get the Sumation of the Fiscal Documents and Add/Subtract them from the Reconciliation Balance
        for (AggregateResult result : [SELECT Reconciliation__c, RecordTypeId, SUM(Amount__c) FROM Ledger_Item__c WHERE Reconciliation__c IN :reconciliationIds GROUP BY Reconciliation__c, RecordTypeId]) {
            curBalance = balance.get((Id)result.get('Reconciliation__c'));
            if (recordTypeMap.get((Id)result.get('RecordTypeId')) == 'debit') {
                curBalance.put('debits', curBalance.get('debits') + (Decimal)result.get('expr0'));
            } else if (recordTypeMap.get((Id)result.get('RecordTypeId')) == 'credit') {
                curBalance.put('credits', curBalance.get('credits') + (Decimal)result.get('expr0'));
            }
            balance.put((Id)result.get('Reconciliation__c'), curBalance);
        }
        
        for (Id curId : balance.keySet()) {
            balance.get(curId).put('balance', balance.get(curId).get('credits') - balance.get(curId).get('debits'));
        }
        
        return balance;
    }
    
    public static void reconcileReconciliation(Set<Id> reconciliationIds) {
        for (Id reconciliationId : reconciliationIds) {
            //Check the IDs are Valid
            if (reconciliationId.getSObjectType().getDescribe().getName() != 'Reconciliation__c') {
                //throw new Exception('ID is not a valid Reconciliation__c ID');
            }
        }
        
        List<Reconciliation__c> reconciliationsToUpdate = new List<Reconciliation__c>();
        Map<Id, Map<String, Decimal>> balance = Reconciliation.calculateBalance(reconciliationIds);
        for (Reconciliation__c reconciliation : [SELECT Id, Reconciled__c FROM Reconciliation__c WHERE Id IN :reconciliationIds]) {
            //if (balance.get(reconciliation.Id).get('balance') == 0) {
            if (balance.get(reconciliation.Id).get('balance') == 0 && balance.get(reconciliation.Id).get('credits') > 0 && balance.get(reconciliation.Id).get('debits') > 0) {
                reconciliation.Reconciled__c = true;
            } else {
                reconciliation.Reconciled__c = false;
            }
            reconciliation.Credits__c = balance.get(reconciliation.Id).get('credits');
            reconciliation.Debits__c = balance.get(reconciliation.Id).get('debits');
            reconciliationsToUpdate.add(reconciliation);
        }
        
        update reconciliationsToUpdate;
    }*/
    
    public static void unreconcileReconciliations(Set<Id> reconciliationIds) { //unreconcile and delete
        if(reconciliationIds.isEmpty()) {
            return;
        }
        
        List<Reconciliation__c> reconciliations = new List<Reconciliation__c>([SELECT Id, Account__c, Reconciled__c, (SELECT Id, Amount__c, Fiscal_Document__c, Payment__c, Refund__c, Reconciliation__c FROM Ledger_Items__r) FROM Reconciliation__c WHERE Id IN :reconciliationIds]);
        List<Ledger_Item__c> ledgerItems = new List<Ledger_Item__c>();
        Set<Id> accountIds = new Set<Id>();
        
        for(Reconciliation__c reconciliation: reconciliations) {
            reconciliation.Reconciled__c = false;
            accountIds.add(reconciliation.Account__c);
            ledgerItems.addAll(reconciliation.Ledger_Items__r);
        }
        update reconciliations;
        
        List<Id> fiscalDocuments = new List<Id>();
        List<Id> payments = new List<Id>();
        List<Id> refunds = new List<Id>();
        
        if(ledgerItems.size() > 0) {
            for(Ledger_Item__c item: ledgerItems) {
                if(item.Fiscal_Document__c != null) {
                    fiscalDocuments.add(item.Fiscal_Document__c);
                }
                
                if(item.Payment__c != null) {
                    payments.add(item.Payment__c);
                }
                
                if(item.Refund__c != null) {
                    refunds.add(item.Refund__c);
                }
            }
            
            if(fiscalDocuments.size() > 0) {
                LedgerItem.removeReconciliation(fiscalDocuments);
            }
            
            if(payments.size() > 0) {
                LedgerItem.removeReconciliation(payments);
            }
            
            if(refunds.size() > 0) {
                LedgerItem.removeReconciliation(refunds);
            }
        }
        delete reconciliations;
        
        if(!accountIds.isEmpty()) {
            //LedgerItem.matchLedgerItems(accountIds, new Set<Id>(), new Set<Id>()); //fix the looping error before enabling this line
        }
    }
}