src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <formula>Subtotal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Subscriber__c.object
<CustomObject>
    <description>DO NOT USE: Depreciated in favour of LoRaWAN Tenancies &amp; Packages.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LoRaWAN Subscribers</relationshipLabel>
        <relationshipName>LoRaWAN_Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <description>How long is customer committed for</description>
        <label>Commitment</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Year</fullName>
                </value>
                <value>
                    <fullName>3 Years</fullName>
                </value>
                <value>
                    <fullName>5 Years</fullName>
                </value>
                <value>
                    <fullName>No Commitment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Rate__c</fullName>
        <label>Device Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fair_Usage_Limit__c</fullName>
        <defaultValue>60</defaultValue>
        <description>Expected maximum number of messages per day under the fair FUP (Fair Usage Policy)</description>
        <label>Fair Usage Limit</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message_Rate__c</fullName>
        <defaultValue>0.05</defaultValue>
        <label>Message Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overage_Rate__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Charge per message over the FUP (Fair Usage Policy)</description>
        <label>Overage Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LoRaWAN Subscriber</label>
    <nameField>
        <label>LoRaWAN Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LorawanInvoiceService.cls
@RestResource(urlMapping='/ThingParkBillingService/LorawanInvoice/*')
global with sharing class LorawanInvoiceService {
    
    @HttpGet
    global static Fiscal_Document__c[] doGet() {
        RestRequest request = RestContext.request;
        System.debug('request : ' + request);
        System.debug('request.requestURI : ' + request.requestURI);
        Integer idStart = request.requestURI.lastIndexOf('/')+1;
        String id = request.requestURI.substring(idStart);
        Fiscal_Document__c[] results = [SELECT Id, Name, Description__c, Account__c, Total_Value__c FROM Fiscal_Document__c];
        System.debug('Fiscal_Document__c' + results);
        return results;
    }
    
    @HttpPost
    global static String doPost(String name) {
        RestRequest request = RestContext.request;
        System.debug('request : ' + request);
        System.debug('request.requestURI : ' + request.requestURI);

        // Integer idStart = request.requestURI.lastIndexOf('/')+1;
        // String id = request.requestURI.substring(idStart);
        // System.debug('request.requestURI : ' + request.requestURI);
        
        // LoRaWAN_Subscriber__c subscriber = new LoRaWAN_Subscriber__c();
        // Name, Device_Rate__c, Account__c, Message_Rate__c, Commitment__c, Overage_Rate__c, Fair_Usage_Limit__c
        // subscriber.Name = name;
        // insert subscriber;
        // return subscriber.Id;
        return name;
    }
    
    @HttpDelete
    global static void doDelete() {
        RestRequest request = RestContext.request;
        System.debug('request : ' + request);
        System.debug('request.requestURI : ' + request.requestURI);

        // Integer idStart = request.requestURI.lastIndexOf('/')+1;
        // String id = request.requestURI.substring(idStart);
        // System.debug('request.requestURI : ' + request.requestURI);

        // LoRaWAN_Subscriber__c subscriber = [SELECT Id, Name FROM LoRaWAN_Subscriber__c WHERE Id = :id];
        // System.debug('delete : ' + subscriber);
        // delete subscriber;
    }
}