src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>Reconciliation__r.Reconciled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FiscalDocument.cls
public class FiscalDocument {
	
	public static void calculateAmountAllocated(Set<Id> fiscalDocumentIds) {
		//Fiscal Document Id => Fiscal Document
		Map<Id, Fiscal_Document__c> fiscalDocumentMap = new Map<Id, Fiscal_Document__c>();
		fiscalDocumentMap.putAll([SELECT Id, Amount_Allocated__c FROM Fiscal_Document__c WHERE Id IN :fiscalDocumentIds]);
		//Fiscal Document Id => Amount ALlocated
		Map<Id, Decimal> fiscalDocumentAmountAllocated = new Map<Id, Decimal>();
		
        for (Id fdId : fiscalDocumentMap.keySet()) {
			fiscalDocumentAmountAllocated.put(fdId, 0.00);
		}
        
		//Calculate the Correct Amount's Allocated
		for (Ledger_Item__c item : [SELECT Id, Amount__c, Fiscal_Document__c FROM Ledger_Item__c WHERE Reconciled__c = true AND Fiscal_Document__c IN :fiscalDocumentIds]) {
			fiscalDocumentAmountAllocated.put(item.Fiscal_Document__c, fiscalDocumentAmountAllocated.get(item.Fiscal_Document__c) + item.Amount__c);
		}
		
		//Check the Fiscal Document Amount Allocated Matches the Amount Allocated just Computed
		List<Fiscal_Document__c> fiscalDocumentsToUpdate = new List<Fiscal_Document__c>();
		for (Fiscal_Document__c fiscalDocument : fiscalDocumentMap.values()) {
			if (fiscalDocument.Amount_Allocated__c != fiscalDocumentAmountAllocated.get(fiscalDocument.Id)) {
				fiscalDocument.Amount_Allocated__c = fiscalDocumentAmountAllocated.get(fiscalDocument.Id);
				fiscalDocumentsToUpdate.add(fiscalDocument);
			}
		}
		
		if (!fiscalDocumentsToUpdate.isEmpty()) {
			update fiscalDocumentsToUpdate;
		}
		
	}
	
}