src/objects/Fiscal_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fiscal Documents</relationshipLabel>
        <relationshipName>Fiscal_Documents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>to be matched with payment.description</description>
        <label>Description</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Dispute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <label>Fiscal Document</label>
    <nameField>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Documents</pluralLabel>
    <recordTypes>
        <fullName>sales_invoice</fullName>
        <active>true</active>
        <label>Sales Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fiscal_Document_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Document__c</fullName>
        <label>Fiscal Document</label>
        <referenceTo>Fiscal_Document__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tax</label>
        <referenceTo>Tax__c</referenceTo>
        <relationshipLabel>Fiscal Document Lines</relationshipLabel>
        <relationshipName>Fiscal_Document_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fiscal Document Line</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiscal Document Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThingParkInvoice.cls
public class ThingParkInvoice {
    private static ThingParkInvoiceConfig config = ThingParkInvoiceConfig.selectCurrent();
    private static List<Product2> lorawanProducts = [SELECT Id, Name, Description, Family, ProductCode, IsActive FROM Product2 WHERE Family = 'LORAWAN' AND IsActive = true];
    private static RecordType recordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Fiscal_Document__c' AND DeveloperName = 'sales_invoice'];
    private static Tax__c vatRate = [SELECT Id, Name, Rate__c FROM Tax__c LIMIT 1];
    private Fiscal_Document__c invoice = null;

    private ThingParkInvoice(final Fiscal_Document__c invoice) {
        this.invoice = invoice;
    }

    public static ThingParkInvoice create(final String accountId, final String description) {
        if (accountId != null) {
            // When we create an invoice for the service usage
            final Fiscal_Document__c invoice = new Fiscal_Document__c(
                Account__c = accountId,
                Description__c = description,
                RecordTypeId = recordType.Id,
                Draft__c = true,
                Dispute__c = false);
            insert invoice;
            
            return new ThingParkInvoice(invoice);            
        }
        return null;
    }

    public ThingParkInvoice addServiceCharges(final String productId, final Decimal qty) {
        // @todo: look up product description & charges
        final String description = 'Service';
        Decimal amount = 0.00;
        return addLine(description, productId, qty, amount);
    }

    public ThingParkInvoice addDeviceCharges(final String productId, final Decimal qty) {
        // @todo: look up product description & charges
        final String description = 'Devices';
        final Decimal amount = 2.00;
        return addLine(description, productId, qty, amount);
    }

    public ThingParkInvoice addOverageCharges(final String productId, final Decimal qty) {
        // @todo: look up product description & charges
        final String description = 'Overage';
        final Decimal amount = 4.00;
        return addLine(description, productId, qty, amount);
    }
    
    public ThingParkInvoice addEndOfLifeCharges(final String productId, final Decimal qty) {
        // @todo: look up product description & charges
        final String description = 'End of life';
        final Decimal amount = 8.00;
        return addLine(description, productId, qty, amount);
    }
    
    private ThingParkInvoice addLine(final String description, final String productId, final Decimal qty, final Decimal amount) {
        final Fiscal_Document_Line__c invoiceLine = new Fiscal_Document_Line__c(
            Fiscal_Document__c = invoice.id,
            Description__c = description,
            Product__c = productId,
            Quantity__c = qty,
            Amount__c = amount,
            Tax__c = vatRate.Id);
        return this;
    }
}