src/objects/Go_Cardless__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Api_Token__c</fullName>
        <label>Api Token</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Api_Url__c</fullName>
        <label>Api Url</label>
        <length>35</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Api_Version__c</fullName>
        <label>Api Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Go Cardless</label>
</CustomObject>

src/classes/GoCardlessAPITestClass.cls
@isTest
private class GoCardlessAPITestClass {

    static testMethod void testApi() {
        Test.setMock(HttpCalloutMock.class, new GoCardlessMockHttpResponseGenerator());
        
    	Go_Cardless__c setting = new Go_Cardless__c(Name = 'default', Api_Url__c = 'url', Api_Token__c = 'token', Api_Version__c = 'version');
    	insert setting;
    	
    	Test.startTest();
    	
    	GoCardlessAPI.getBankAccount('BA0001');
        GoCardlessAPI.getCustomerBankAccounts('CU0001');
        GoCardlessAPI.getCustomerPayments('CU0001');
        GoCardlessAPI.getCustomerRefunds('PM0001');
        GoCardlessAPI.getCustomerBankAccountMandates('BA0001');
        GoCardlessAPI.disableCustomerBankAccount('BA0001');
        GoCardlessAPI.getCustomerMandates('CU0001');
        GoCardlessAPI.isValidGoCardlessID('CU0001');
        GoCardlessAPI.getCustomerBankAccountMandates('BA0001');
        GoCardlessAPI.createCustomerPayment('CU0001', 5, 'test', null);
        GoCardlessAPI.createCustomerRefund('PM0001', 5, 'test');
        
        Test.stopTest();
    }
}