src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>Reconciliation__r.Reconciled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Payment.cls
public class Payment {
	
	public static void calculateAmountAllocated(Set<Id> paymentIds) {
		//Fiscal Document Id => Fiscal Document
		Map<Id, Payment__c> paymentMap = new Map<Id, Payment__c>();
		paymentMap.putAll([SELECT Id, Amount_Allocated__c FROM Payment__c WHERE Id IN :paymentIds]);
		//Fiscal Document Id => Amount ALlocated
		Map<Id, Decimal> paymentAmountAllocated = new Map<Id, Decimal>();
        
        for (Id paymentId : paymentMap.keySet()) {
			paymentAmountAllocated.put(paymentId, 0.00);
		}
		
		//Calculate the Correct Amount's Allocated
		for (Ledger_Item__c item : [SELECT Id, Amount__c, Payment__c, Reconciled__c FROM Ledger_Item__c WHERE Reconciled__c = true AND Payment__c IN :paymentIds]) {
            paymentAmountAllocated.put(item.Payment__c, paymentAmountAllocated.get(item.Payment__c) + item.Amount__c);
		}
		
		//Check the Fiscal Document Amount Allocated Matches the Amount Allocated just Computed
		List<Payment__c> paymentsToUpdate = new List<Payment__c>();
		for (Payment__c payment : paymentMap.values()) {
			if (payment.Amount_Allocated__c != paymentAmountAllocated.get(payment.Id)) {
				payment.Amount_Allocated__c = paymentAmountAllocated.get(payment.Id);
				paymentsToUpdate.add(payment);
			}
		}
		
		if (!paymentsToUpdate.isEmpty()) {
			update paymentsToUpdate;
		}
	}
    
}