src/objects/Ledger_Item__c.object
<CustomObject>
    <description>Holds credit and debit entries for Fiscal documents and Payments.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Credit/Debit Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reconciled__c</fullName>
        <formula>Reconciliation__r.Reconciled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reconciled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Refund__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Refund</label>
        <referenceTo>Refund__c</referenceTo>
        <relationshipLabel>Ledger Items</relationshipLabel>
        <relationshipName>Ledger_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ledger Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledger Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Allocated</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>RF-{0000}</displayFormat>
        <label>Refund Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Refund.cls
public class Refund {
	
	public static void calculateAmountAllocated(Set<Id> refundIds) {
		//Fiscal Document Id => Fiscal Document
		Map<Id, Refund__c> refundMap = new Map<Id, Refund__c>();
		refundMap.putAll([SELECT Id, Amount_Allocated__c FROM Refund__c WHERE Id IN :refundIds]);
		//Fiscal Document Id => Amount ALlocated
		Map<Id, Decimal> refundAmountAllocated = new Map<Id, Decimal>();
        
		//Populate the Fiscal Document Id => Amount Allocated Mapping
		for (Id refundId : refundMap.keySet()) {
			refundAmountAllocated.put(refundId, 0.00);
		}
		
		//Calculate the Correct Amount's Allocated
		for (Ledger_Item__c item : [SELECT Id, Amount__c, Refund__c FROM Ledger_Item__c WHERE Reconciled__c = true AND Refund__c IN :refundIds]) {
            if(refundAmountAllocated.containsKey(item.Refund__c)) {
                refundAmountAllocated.put(item.Refund__c, refundAmountAllocated.get(item.Refund__c) + item.Amount__c);
            } else {
                refundAmountAllocated.put(item.Refund__c, item.Amount__c);
            }
        }
		
		//Check the Fiscal Document Amount Allocated Matches the Amount Allocated just Computed
		/*List<Refund__c> refundsToUpdate = new List<Refund__c>();
		for (Refund__c refund : refundMap.values()) {
			if (refund.Amount_Allocated__c != refundAmountAllocated.get(refund.Id)) {
				refund.Amount_Allocated__c = refundAmountAllocated.get(refund.Id);
				refundsToUpdate.add(refund);
			}
		}*/
        
        List<Refund__c> refundsToUpdate = new List<Refund__c>();
		for (Refund__c refund : refundMap.values()) {
			if (refund.Amount_Allocated__c != refundAmountAllocated.get(refund.Id)) {
				if (refundAmountAllocated.get(refund.Id) == null) {
					refund.Amount_Allocated__c = 0.00;
				} else {
					refund.Amount_Allocated__c = refundAmountAllocated.get(refund.Id);
				}
				refundsToUpdate.add(refund);
			}
		}
		
		if (!refundsToUpdate.isEmpty()) {
			update refundsToUpdate;
		}
	}
}