src/objects/LoRaWAN_Package__c.object
<CustomObject>
    <description>Represents a ThingPark Order, a subscriber can have multiple orders.</description>
    <fields>
        <fullName>LoRaWAN_Tenancy__c</fullName>
        <description>The Tenancy this Package is attached to.</description>
        <label>LoRaWAN Tenancy</label>
        <referenceTo>LoRaWAN_Tenancy__c</referenceTo>
        <relationshipLabel>LoRaWAN Package</relationshipLabel>
        <relationshipName>LoRaWAN_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>LoRaWAN Package</label>
    <nameField>
        <label>LoRaWAN Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThingParkTest.cls
@isTest public class ThingParkTest {

	@isTest static void testAddTenancy() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.addTenancy(new LoRaWAN_Tenancy__c());
		System.assertEquals(201, result.getStatusCode(), 'Expected 201 status code.');

		Test.stopTest();
    }

    @isTest static void testGetTenancy() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.getTenancy(new LoRaWAN_Tenancy__c());
        System.assertEquals(200, result.getStatusCode(), 'Expected 200 status code.');

		Test.stopTest();
    }

    @isTest static void testUpdateTenancy() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.updateTenancy(new LoRaWAN_Tenancy__c());
        System.assertEquals(200, result.getStatusCode(), 'Expected 200 status code.');

		Test.stopTest();
    }

	@isTest static void testAddOrder() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.addOrder(new LoRaWAN_Package__c());
		System.assertEquals(201, result.getStatusCode(), 'Expected 201 status code.');

		Test.stopTest();
    }

    @isTest static void testGetOrder() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.getOrder(new LoRaWAN_Package__c());
        System.assertEquals(200, result.getStatusCode(), 'Expected 200 status code.');

		Test.stopTest();
    }

    @isTest static void testUpdateOrder() {
		Test.startTest();
		ThingParkDxRestMock mock = createMock();

        HttpResponse result = ThingParkREST.updateOrder(new LoRaWAN_Package__c());
        System.assertEquals(200, result.getStatusCode(), 'Expected 200 status code.');

		Test.stopTest();
    }
    
    private static ThingParkDxRestMock createMock() {        
		// Create the mock response based on a static resource
        // WebServiceMock mock = new ThingParkDxRestMock();
		// Test.setMock(WebServiceMock.class, mock);        
        // mock.setStatusCode(200);
        // mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // return mock;
        return new ThingParkDxRestMock();
    }

}