src/objects/LoRaWAN_Package__c.object
<CustomObject>
    <description>Represents a ThingPark Order, a subscriber can have multiple orders.</description>
    <fields>
        <fullName>Device_Rate__c</fullName>
        <label>Device Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Device_Rate_after_commitment_end__c</fullName>
        <label>Device Rate after commitment end</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LoRaWAN_Tenancy__c</fullName>
        <description>The Tenancy this Package is attached to.</description>
        <label>LoRaWAN Tenancy</label>
        <referenceTo>LoRaWAN_Tenancy__c</referenceTo>
        <relationshipLabel>LoRaWAN Package</relationshipLabel>
        <relationshipName>LoRaWAN_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Of_Devices__c</fullName>
        <label>Quantity Of Devices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>length of the commitment in months.</description>
        <label>Term</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LoRaWAN Package</label>
    <nameField>
        <label>LoRaWAN Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <fields>
        <fullName>Actility_Subscriber_ID__c</fullName>
        <label>Actility Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActilityOrderForPackageTest.cls
@isTest public class ActilityOrderForPackageTest extends AbstractThingParkTestCase {
    
    @isTest static void testOrderInsertTrigger() {
        Test.startTest();
        
        assertNotNull(createMock());
        
        ExpectedDataManager expectedData = new ExpectedDataManager();
        
        system.runAs(expectedData.givenTestUser()) {
            expectedData.givenThingParkPackage();
            // implies expectedData.givenThingParkTenancy();
            // implies expectedData.givenThingParkProduct();
            // implies expectedData.givenThingParkCustomer();
            expectedData.givenInvoiceVatRate();
            expectedData.givenInvoiceRecordType();
            System.debug('Given the expected test data : ' + expectedData);
            
            LoRaWAN_Package__c lorawanPackage = new LoRaWAN_Package__c();
            lorawanPackage.LoRaWAN_Tenancy__c = expectedData.lorawanTenancy.Id;
            // lorawanPackage.Actility_Subscription_ID__c = expectedData.lorawanTenancy.Actility_Subscriber_ID__c;
            lorawanPackage.Name = 'Test-Package' + Timestamp.timeStamp();
            lorawanPackage.Device_Rate__c = 0.05;
            lorawanPackage.Device_Rate_after_commitment_end__c = 0.10;
            lorawanPackage.Start_Date__c = System.today();
            lorawanPackage.Term__c = 12;
            lorawanPackage.Quantity_Of_Devices__c = 10;
            insert lorawanPackage;
            System.debug('Order created: ' + lorawanPackage);
            // @todo check actililty subscriber ID
        }
        Test.stopTest();
    }
    
    @isTest static void testOrderUpdateTrigger() {
        Test.startTest();
        
        ExpectedDataManager expectedData = new ExpectedDataManager();
        
        system.runAs(expectedData.givenTestUser()) {
            expectedData.givenThingParkPackage();
            // implies expectedData.givenThingParkTenancy();
            // implies expectedData.givenThingParkProduct();
            // implies expectedData.givenThingParkCustomer();
            expectedData.givenInvoiceVatRate();
            expectedData.givenInvoiceRecordType();
            System.debug('Given the expected test data : ' + expectedData);
            
            assertNotNull(createMock());

            LoRaWAN_Package__c lorawanPackage = expectedData.lorawanPackage;
            lorawanPackage.LoRaWAN_Tenancy__c = expectedData.lorawanTenancy.Id;
            // lorawanPackage.Actility_Subscription_ID__c = expectedData.lorawanTenancy.Actility_Subscriber_ID__c;
            lorawanPackage.Name = 'Test-Package' + Timestamp.timeStamp();
            lorawanPackage.Device_Rate__c = 0.10;
            lorawanPackage.Device_Rate_after_commitment_end__c = 0.99;
            lorawanPackage.Start_Date__c = System.today();
            lorawanPackage.Term__c = 60;
            lorawanPackage.Quantity_Of_Devices__c = 99;
            update lorawanPackage;
            System.debug('package updated: ' + lorawanPackage);
            // @todo check actililty subscriber ID
        }
        Test.stopTest();
    }    
}