src/objects/LoRaWAN_Package__c.object
<CustomObject>
    <description>Represents a ThingPark Order, a subscriber can have multiple orders.</description>
    <fields>
        <fullName>Actility_Order_ID__c</fullName>
        <label>Actility Order ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Device_Rate__c</fullName>
        <label>Device Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Device_Rate_after_commitment_end__c</fullName>
        <label>Device Rate after commitment end</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>ADDMONTHS( Start_Date__c ,  Term__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LoRaWAN_Tenancy__c</fullName>
        <description>The Tenancy this Package is attached to.</description>
        <label>LoRaWAN Tenancy</label>
        <referenceTo>LoRaWAN_Tenancy__c</referenceTo>
        <relationshipLabel>LoRaWAN Package</relationshipLabel>
        <relationshipName>LoRaWAN_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Push_to_Actility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Push Package changes to Actility ThingPark</description>
        <label>Push to Actility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quantity_Of_Devices__c</fullName>
        <label>Quantity Of Devices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(is_Cancelled__c, &quot;Cancelled&quot;, IF(is_Active__c, &quot;Active&quot;, &quot;Draft&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>length of the commitment in months.</description>
        <label>Term</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The device is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <label>LoRaWAN Package</label>
    <nameField>
        <label>LoRaWAN Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LorawanPackageService.cls
@RestResource(urlMapping='/ThingParkBillingService/LorawanPackages/*')
global with sharing class LorawanPackageService {
    static String regExp = '\\/ThingParkBillingService\\/LorawanPackages\\/(\\d+)';

    @HttpGet global static LoRaWAN_Package__c[] doGet() {
        final RestRequest request = RestContext.request;
        final RestResponse response = RestContext.response;
        if (System.Pattern.matches(regExp, request.requestURI)) {
            final String id = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);

            return [SELECT Id, Name, 
                    	LoRaWAN_Tenancy__c, LoRaWAN_Tenancy__r.Id, LoRaWAN_Tenancy__r.Name, 
                        Actility_Order_ID__c, Start_Date__c, Term__c, End_Date__c,
                        Quantity_Of_Devices__c, Device_Rate__c, Device_Rate_after_commitment_end__c,
                        is_Active__c, is_Cancelled__c, Status__c, Push_to_Actility__c
                    FROM LoRaWAN_Package__c 
                    WHERE id=:id];
        } else {
            return [SELECT Id, Name, 
                    	LoRaWAN_Tenancy__c, LoRaWAN_Tenancy__r.Id, LoRaWAN_Tenancy__r.Name, 
                        Actility_Order_ID__c, Start_Date__c, Term__c, End_Date__c,
                        Quantity_Of_Devices__c, Device_Rate__c, Device_Rate_after_commitment_end__c,
                        is_Active__c, is_Cancelled__c, Status__c, Push_to_Actility__c
                    FROM LoRaWAN_Package__c];
        }
    }
}