src/objects/LoRaWAN_Package__c.object
<CustomObject>
    <description>Represents a ThingPark Order, a subscriber can have multiple orders.</description>
    <fields>
        <fullName>Device_Rate__c</fullName>
        <label>Device Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Device_Rate_after_commitment_end__c</fullName>
        <label>Device Rate after commitment end</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>ADDMONTHS( Start_Date__c ,  Term__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LoRaWAN_Tenancy__c</fullName>
        <description>The Tenancy this Package is attached to.</description>
        <label>LoRaWAN Tenancy</label>
        <referenceTo>LoRaWAN_Tenancy__c</referenceTo>
        <relationshipLabel>LoRaWAN Package</relationshipLabel>
        <relationshipName>LoRaWAN_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Of_Devices__c</fullName>
        <label>Quantity Of Devices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(is_Cancelled__c, &quot;Cancelled&quot;, IF(is_Active__c, &quot;Active&quot;, &quot;Draft&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>length of the commitment in months.</description>
        <label>Term</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The device is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <label>LoRaWAN Package</label>
    <nameField>
        <label>LoRaWAN Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Customer Account this Tenancy is attached to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LoRaWAN Tenancies</relationshipLabel>
        <relationshipName>LoRaWAN_Tenancies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actility_Subscriber_ID__c</fullName>
        <label>Actility Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Max_Average__c</fullName>
        <defaultValue>60</defaultValue>
        <description>The maximum number of message per day averaged over the month.</description>
        <label>Daily Max Average</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overage_Rate__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Overage Rate per message above the FUP (Fair Usage Policy).</description>
        <label>Overage Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Devices__c</fullName>
        <description>Total number of devices for all packages for this tenancy.</description>
        <label>Total Devices</label>
        <summarizedField>LoRaWAN_Package__c.Quantity_Of_Devices__c</summarizedField>
        <summaryForeignKey>LoRaWAN_Package__c.LoRaWAN_Tenancy__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ThingParkREST.cls
public class ThingParkREST {

    private static ThingParkConfig config = new ThingParkConfig();

    public static String authorise() {
        // prepare authorisation uri for ThingPark
        String serviceUrl = ThingParkREST.makeUri('/admin/{version}/oauth/token');
        System.debug('ThingParkREST authorise : ' + serviceUrl );

		String parameters = new QueryMaker()
            .add('grant_type=client_credentials')
            .add('client_id', config.clientId())
            .add('client_secret', config.clientSecret())
            .asString();
        System.debug('ThingParkREST authorise parameters : ' + parameters );

        Http http = new Http();
        HttpRequest get_request = new HttpRequest();
        String fullUrl = serviceUrl+parameters;
        System.debug('ThingParkREST fullUrl : ' + fullUrl);

        get_request.setEndpoint(fullUrl);
        get_request.setMethod('POST');
        get_request.setBody(parameters);

        Map<String, Object> responseData = dataFromResponse(http.send(get_request));

        return (String) responseData.get('access_token');
    }

    public static Boolean addTenancy(final LoRaWAN_Tenancy__c item) {
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/subscribers/');

        // prepare json
        String json = makeRequestJsonForTenancy(item);
        System.debug(json);

        Map<String, Object> responseData = ThingParkREST.makeDxPostRequest(serviceUrl, json);

        return true;
    }

    public static Boolean getTenancy(final LoRaWAN_Tenancy__c item) {
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/subscribers/');

        Map<String, Object> responseData = ThingParkREST.makeDxGetRequest(serviceUrl);

        return true;
    }
    
    public static Boolean updateTenancy(final LoRaWAN_Tenancy__c item) {
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/subscribers/');

        // prepare json
        String json = makeRequestJsonForTenancy(item);
        System.debug(json);

        Map<String, Object> responseData = ThingParkREST.makeDxPutRequest(serviceUrl, json);

        return true;
    }

    private static String makeRequestJsonForTenancy(final LoRaWAN_Tenancy__c item) {
        // Available fields:
        //  Account__c
        //  Actility_Subscriber_ID__c
        //  Id
        //  Name
        //  Total_Devices__c
        //  Daily_Max_Average__c
        //  Overage_Rate__c
        // final String json = JSON.serialize(item);
        final String json = '{"primaryUser": {"firstName": "Alice", "lastName": "Automation","email": "alice.automation@connexin.co.uk","organization": "Connexin Company UK","password": "DQ2sO83zXY"}}';
        System.debug(json);
        return json;
    }

    public static Boolean addOrder(final LoRaWAN_Package__c item) {
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/orders/');

        // prepare json
        String json = makeJsonForOrder(item);
        System.debug(json);

        Map<String, Object> responseData = ThingParkREST.makeDxPostRequest(serviceUrl, json);

        return true;
    }
    
    public static Boolean getOrder(final LoRaWAN_Package__c item) {

        final String accessToken = authorise();
        
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/orders/');

        // prepare json
        String json = makeJsonForOrder(item);
        System.debug(json);

        Map<String, Object> responseData = ThingParkREST.makeDxGetRequest(serviceUrl);

        return true;
    }
    
    public static Boolean updateOrder(final LoRaWAN_Package__c item) {
        // prepare service url
        String serviceUrl = ThingParkREST.makeUri('/core/{version}/orders/');

        // prepare json
        String json = makeJsonForOrder(item);
        System.debug(json);

        Map<String, Object> responseData = ThingParkREST.makeDxPutRequest(serviceUrl, json);

        return true;
    }

    private static String makeUri(final string resourceUri) {
        return config.endpoint() + resourceUri.replace('{version}', config.version());
    }
    
    private static String makeJsonForOrder(final LoRaWAN_Package__c item) {
        // Available fields:            
        //  Id,
        //  Name,
        //  Actility_Subscription_ID__c,
        //  LoRaWAN_Tenancy__c,
        //  Start_Date__c,
        //  Term__c
        //  End_Date__c,
        //  Quantity_Of_Devices__c,            
        //  Device_Rate__c,
        //  Device_Rate_after_commitment_end__c,
        //  Status__c,
        //  is_Active__c,
        //  is_Cancelled__c,
        // final String json = JSON.serialize(item);

        final String json = ' { "name":"New OTAA device", "EUI":"0018A20000000004", "activationType":"OTAA", "deviceProfileId":"ADRF/DemonstratorA.1_EU", "applicationEUI": "70B3D53260000003",  "applicationKey": "258DB54023EA74F0D55085F7351737D0"}';
        System.debug(json);        
        return json;
    }

    private static Map<String, Object> makeDxGetRequest(final String serviceUrl) {
        final String accessToken = authorise();

        Http http = new Http();
        HttpRequest get_request = new HttpRequest();
        get_request.setEndpoint(serviceUrl);
        get_request.setMethod('GET');
        get_request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        get_request.setHeader('Authorization', 'Bearer '+ accessToken);

        HttpResponse response = http.send(get_request);

        System.assertEquals(200, response.getStatusCode());
		System.assertEquals('application/json;charset=UTF-8',
                            response.getHeader('Content-Type'),
                            'Unexpected Content-Type value :' + response.getHeader('Content-Type'));

        return dataFromResponse(response);
    }
    
    private static Map<String, Object> makeDxPostRequest(final String serviceUrl, final String json) {
        final String accessToken = authorise();

        Http http = new Http();        
        HttpRequest post_request = new HttpRequest();
        post_request.setEndpoint(serviceUrl);
        post_request.setMethod('POST');
        post_request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        post_request.setHeader('Authorization', 'Bearer '+ accessToken);
        post_request.setBody(json);

        HttpResponse response = http.send(post_request);

        System.assertEquals(201, response.getStatusCode());
		System.assertEquals('application/json;charset=UTF-8',
                            response.getHeader('Content-Type'),
                            'Unexpected Content-Type value :' + response.getHeader('Content-Type'));

        return dataFromResponse(response);
    }

    private static Map<String, Object> makeDxPutRequest(final String serviceUrl, final String json) {
        final String accessToken = authorise();
        
        Http http = new Http();        
        HttpRequest post_request = new HttpRequest();
        post_request.setEndpoint(serviceUrl);
        post_request.setMethod('PUT');
        post_request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        post_request.setHeader('Authorization', 'Bearer '+ accessToken);
        post_request.setBody(json);

        HttpResponse response = http.send(post_request);

        System.assertEquals(200, response.getStatusCode());
		System.assertEquals('application/json;charset=UTF-8',
                            response.getHeader('Content-Type'),
                            'Unexpected Content-Type value :' + response.getHeader('Content-Type'));

        return dataFromResponse(response);
    }

    private static Map<String, Object> dataFromResponse(final HttpResponse response) {
        String body = response.getBody(); 
        System.debug('response.getBody() = ' + body);        

        Map<String, Object> jsonData = (Map<String, Object>) JSON.deserializeUntyped(body);
        System.debug('jsonData = ' + jsonData);

        return jsonData;
    }

    public static Boolean thingParkWithCallout(final LoRaWAN_Tenancy__c item) {
		HttpRequest request = new HttpRequest();
		request.setEndpoint('callout:thingpark/some_path');
		request.setMethod('GET');
		Http http = new Http();
		HTTPResponse response = http.send(request);
		System.debug(response.getBody());
        return true;
    }
    
}