src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Customer Account this Tenancy is attached to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LoRaWAN Tenancies</relationshipLabel>
        <relationshipName>LoRaWAN_Tenancies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Daily_Max_Average__c</fullName>
        <defaultValue>60</defaultValue>
        <description>The maximum number of message per day averaged over the month.</description>
        <label>Daily Max Average</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overage_Rate__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Overage Rate per message above the FUP (Fair Usage Policy).</description>
        <label>Overage Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActilitySubscriberForTenancyTest.cls
@isTest public class ActilitySubscriberForTenancyTest extends AbstractThingParkTestCase {

    @isTest static void testTenancyInsertTrigger() {
		Test.startTest();

		assertNotNull(createMock());
        
		ExpectedDataManager expectedData = new ExpectedDataManager();
        
        system.runAs(expectedData.givenTestUser()) {
            expectedData.givenThingParkProducts();
            expectedData.givenThingParkCustomer();
            expectedData.givenCustomerContacts();
            System.debug('Given the expected test data : ' + expectedData);

            // When the Tenancy is created in salesforce
            LoRaWAN_Tenancy__c lorawanTenancy = new LoRaWAN_Tenancy__c();
            lorawanTenancy.Account__c = expectedData.account.Id;
            lorawanTenancy.Contact__c = expectedData.primaryContact.Id;
            lorawanTenancy.Name = 'Test-' + Timestamp.timeStamp();
            lorawanTenancy.Daily_Max_Average__c = 99;
            lorawanTenancy.Overage_Rate__c = 0.05;
            insert lorawanTenancy;
            System.debug('tenancy created : ' + lorawanTenancy);
        }
	Test.stopTest();
    }
    
    @isTest static void testTenancyUpdateTrigger() {
		Test.startTest();

		assertNotNull(createMock());

		ExpectedDataManager expectedData = new ExpectedDataManager();
        
        system.runAs(expectedData.givenTestUser()) {
            // Given the expected data
            expectedData.givenThingParkProducts();
            LoRaWAN_Tenancy__c lorawanTenancy = expectedData.givenThingParkTenancy();
            System.debug('Given the expected test data : ' + expectedData);

            // When the Tenancy is updated in salesforce
            lorawanTenancy.Name = 'Test-Update-' + Timestamp.timeStamp();
            lorawanTenancy.Daily_Max_Average__c = 999;
            lorawanTenancy.Overage_Rate__c = 0.10;
            update lorawanTenancy;
            System.debug('tenancy updated: ' + lorawanTenancy);

 			Test.stopTest();
        }
    }
}