src/objects/LoRaWAN_Package__c.object
<CustomObject>
    <description>Represents a ThingPark Order, a subscriber can have multiple orders.</description>
    <fields>
        <fullName>Device_Rate__c</fullName>
        <label>Device Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Device_Rate_after_commitment_end__c</fullName>
        <label>Device Rate after commitment end</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LoRaWAN_Tenancy__c</fullName>
        <description>The Tenancy this Package is attached to.</description>
        <label>LoRaWAN Tenancy</label>
        <referenceTo>LoRaWAN_Tenancy__c</referenceTo>
        <relationshipLabel>LoRaWAN Package</relationshipLabel>
        <relationshipName>LoRaWAN_Package</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity_Of_Devices__c</fullName>
        <label>Quantity Of Devices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <description>length of the commitment in months.</description>
        <label>Term</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LoRaWAN Package</label>
    <nameField>
        <label>LoRaWAN Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoRaWAN_Tenancy__c.object
<CustomObject>
    <description>Represents a ThingPark Subscriber, who may have multiple subscriptions.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Customer Account this Tenancy is attached to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LoRaWAN Tenancies</relationshipLabel>
        <relationshipName>LoRaWAN_Tenancies</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actility_Subscriber_ID__c</fullName>
        <label>Actility Subscriber ID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Max_Average__c</fullName>
        <defaultValue>60</defaultValue>
        <description>The maximum number of message per day averaged over the month.</description>
        <label>Daily Max Average</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overage_Rate__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Overage Rate per message above the FUP (Fair Usage Policy).</description>
        <label>Overage Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LoRaWAN Tenancy</label>
    <nameField>
        <label>LoRaWAN Tenancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoRaWAN Tenancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpectedDataManager.cls
public class ExpectedDataManager extends AbstractThingParkTestCase {
    
    // Given Pricebook2 with LoRaWAN products
    public static Pricebook2 givenTestPriceBook() {    
        Pricebook2 testPricebook = new Pricebook2(
            Name = 'Test Pricebook', 
            IsActive = true);
        insert testPricebook;
        return testPricebook;
    }
    
    public static Product2 givenTestProduct() {    
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            Family = 'Test',
            ProductCode = 'Test ' + RandomData.unique(),
            Description = 'Test Product ' + Timestamp.timestamp(),
            IsActive = true);
        insert testProduct;
        return testProduct;
    }
    
    // Given LoRaWAN products
    // LoRaWan 0	LoRaWan without commitment.	LoRaWAN	LORAWAN00	true
    // LoRaWan 1	LoRaWan 1 year commitment.	LoRaWAN	LORAWAN01	true
    // LoRaWan 3	LoRaWan 3 year commitment.	LoRaWAN	LORAWAN03	true
    // LoRaWan 5	LoRaWan 5 year commitment.	LoRaWAN	LORAWAN05	true
    public static List<Product2> givenThingParkProducts() {
        List<Product2> lorawanProducts = new List<Product2>();
        Product2 testLorawan00Product = new Product2(
            Name = 'LoRaWan 0', 
            ProductCode = 'LORAWAN00',
            Description = 'LoRaWan without commitment.',
            Family = 'LoRaWAN',
            IsActive = true);
        insert testLorawan00Product;
        lorawanProducts.add(testLorawan00Product);
        
        Product2 testLorawan01Product = new Product2(
            Name = 'LoRaWan 1', 
            ProductCode = 'LORAWAN01',
            Description = 'LoRaWan 1 year commitment.',
            Family = 'LoRaWAN',
            IsActive = true);
        insert testLorawan01Product;
        lorawanProducts.add(testLorawan01Product);
        
        Product2 testLorawan03Product = new Product2(
            Name = 'LoRaWan 3',
            ProductCode = 'LORAWAN03',
            Description = 'LoRaWan 3 year commitment.',
            Family = 'LoRaWAN',
            IsActive = true);
        insert testLorawan03Product;
        lorawanProducts.add(testLorawan03Product);
        
        Product2 testLorawan05Product = new Product2(
            Name = 'LoRaWan 5',
            ProductCode = 'LORAWAN05',
            Description = 'LoRaWan 5 year commitment.',
            Family = 'LoRaWAN',
            IsActive = true);
        insert testLorawan05Product;
        lorawanProducts.add(testLorawan05Product);
        
        Product2 testLorawanOverage = new Product2(
            Name = 'LoRaWan Overage', 
            ProductCode = 'LORAWAN99',
            Description = 'LoRaWan Overage.',
            Family = 'LoRaWAN',
            IsActive = true);
        insert testLorawanOverage;
        lorawanProducts.add(testLorawanOverage);
        
        System.debug('lorawanProducts : ' + lorawanProducts);
        
        return lorawanProducts;
    }
    
    public static Account givenThingParkCustomer() {
        Account account = new Account(Name='LoRaWAN Test Customer ' + Timestamp.timestamp());
        insert account;

        System.debug('Account : ' + account);
        
        return account;
    }
    
    public static LoRaWAN_Tenancy__c givenThingParkTennancy() {
        return givenThingParkTennancyFor(givenThingParkCustomer());
    }
    
    public static LoRaWAN_Tenancy__c givenThingParkTennancyFor(final Account account) {
        
        createMock();
        
        LoRaWAN_Tenancy__c tenancy = new LoRaWAN_Tenancy__c();
        tenancy.Account__c = account.Id;
        tenancy.Name = 'Test-' + Timestamp.timeStamp();
        tenancy.Daily_Max_Average__c = 99;
        tenancy.Overage_Rate__c = 0.05;
        insert tenancy;

        System.debug('LoRaWAN_Tenancy__c : ' + tenancy);
        
        return tenancy;
    }
    
    public static LoRaWAN_Package__c givenThingParkPackage() {
        return givenThingParkPackageFor(givenThingParkTennancy());
    }
    
    public static LoRaWAN_Package__c givenThingParkPackageFor(final LoRaWAN_Tenancy__c tenancy) {
        
        createMock();
        
        LoRaWAN_Package__c pckage = new LoRaWAN_Package__c();
        pckage.LoRaWAN_Tenancy__c = tenancy.Id;
        pckage.Actility_Subscription_ID__c = tenancy.Actility_Subscriber_ID__c;
        pckage.Name = 'Test-Package' + Timestamp.timeStamp();
        pckage.Device_Rate__c = 0.05;
        pckage.Device_Rate_after_commitment_end__c = 0.10;
        pckage.Start_Date__c = System.today();
        pckage.Term__c = 12;
        pckage.Quantity_Of_Devices__c = 99;
        
        insert pckage;

        System.debug('LoRaWAN_Package__c : ' + pckage);
        
        return pckage;
    }
    
    public static Tax__c givenInvoiceVatRate() {
        Tax__c vatRate = new Tax__c(Name = 'VAT Test Rate', Rate__c = 20 );
        insert vatRate;
        System.debug('vatRate : ' + vatRate);
        
        return vatRate;
    }    
}