src/objects/Management_Device_Type__c.object
<CustomObject>
    <label>Management Device Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP_Port_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Management_Device_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IP Port Assignments</relationshipLabel>
        <relationshipName>Management_IP_Port_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Management_IP__c</fullName>
        <label>Management IP</label>
        <referenceTo>Management_IP__c</referenceTo>
        <relationshipLabel>Management IP Port Assignments</relationshipLabel>
        <relationshipName>Management_IP_Port_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Management IP Port Assignment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Management IP Port Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManagementIPPortAssignmentController.cls
public class ManagementIPPortAssignmentController {
    
    private ApexPages.StandardController stdController;
    private Management_IP_Port_Assignment__c managementIPPortAssignment;
        
    public ManagementIPPortAssignmentController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        this.managementIPPortAssignment = (Management_IP_Port_Assignment__c)this.stdController.getRecord();
        if (System.currentPageReference().getParameters().get('parentId') != null) {
            this.managementIPPortAssignment.Management_IP__c = System.currentPageReference().getParameters().get('parentId');
        }
        if (this.managementIPPortAssignment.Management_IP__c != null) {
            this.setManagementDeviceType();
        }
    }
    
    public void setManagementDeviceType() {
        Management_IP__c managementIP = [SELECT Id, Device__c FROM Management_IP__c WHERE Id = :this.managementIPPortAssignment.Management_IP__c];
        this.managementIPPortAssignment.Management_Device_Type__c = managementIP.Device__c;
    }
    
    public String getManagementIPPortAssignmentKeyPrefix() {
        return Schema.getGlobalDescribe().get('Management_IP_Port_Assignment__c').getDescribe().getKeyPrefix();
    }
    
}