src/objects/Management_Device_Type__c.object
<CustomObject>
    <label>Management Device Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_Device_Type_Port__c.object
<CustomObject>
    <fields>
        <fullName>Management_Device_Type__c</fullName>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management Device Type Ports</relationshipLabel>
        <relationshipName>Management_Device_Type_Ports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Management Device Type Port</label>
    <nameField>
        <label>Port</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Type Ports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <formula>Hostname__c  &amp; &quot;.&quot; &amp; Site__r.Domain__c</formula>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hostname__c</fullName>
        <label>Hostname</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Site</label>
        <referenceTo>Management_Site__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP_Port_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Connected_Device_Name__c</fullName>
        <formula>IF (Connected_Device__c == null, &apos;&apos;, Connected_Device__r.Management_IP__r.Site__r.Name + &quot; &quot; + Connected_Device__r.Management_IP__r.Hostname__c + &quot; - Port &quot; +  Connected_Device__r.Management_Device_Type_Port__r.Name + IF(Connected_Device__r.Description__c != &quot;&quot;, &quot; (&quot; + Connected_Device__r.Description__c + &quot;)&quot;, &quot;&quot;))</formula>
        <label>Connected Device</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Management_Device_Type_Port__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type Port</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Management_Device_Type__c</field>
                <operation>equals</operation>
                <valueField>Management_Device_Type_Port__c.Management_Device_Type__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Management_Device_Type_Port__c</referenceTo>
        <relationshipLabel>Management IP Port Assignments</relationshipLabel>
        <relationshipName>Management_IP_Port_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Management_Device_Type__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IP Port Assignments</relationshipLabel>
        <relationshipName>Management_IP_Port_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Management_IP__c</fullName>
        <label>Management IP</label>
        <referenceTo>Management_IP__c</referenceTo>
        <relationshipLabel>Management IP Port Assignments</relationshipLabel>
        <relationshipName>Management_IP_Port_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Management_IP__r.Site__r.Name + &quot; &quot; + Management_IP__r.Hostname__c + &quot; - Port &quot; +  Management_Device_Type_Port__r.Name + IF(Description__c != &quot;&quot;, &quot; (&quot; + Description__c + &quot;)&quot;, &quot;&quot;)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <label>Management IP Port Assignment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Management IP Port Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Management_Site__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <formula>IF(Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__c != null, Hostname__c  &amp; &quot;.&quot; &amp; Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c,
IF(Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__c != null, Hostname__c  &amp; &quot;.&quot; &amp; Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c,
IF(Parent_Site__r.Parent_Site__r.Parent_Site__c != null, Hostname__c  &amp; &quot;.&quot; &amp; Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Parent_Site__r.Hostname__c,
IF(Parent_Site__r.Parent_Site__c != null, Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Parent_Site__r.Hostname__c,
IF(Parent_Site__c != null, Hostname__c &amp; &quot;.&quot; &amp; Parent_Site__r.Hostname__c, Hostname__c)))))</formula>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hostname__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Hostname</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Management Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConnectedDeviceLookupController.cls
public class ConnectedDeviceLookupController {

    public List<Management_IP__c> managementIPResults {get;set;}
    public Management_IP__c managementIP {get;set;}
    public Id managementIPId {
        get;
        set {
            managementIPId = value;
            if (value != null) {
                this.managementIP = [SELECT Id, Name, Domain__c, Device__c, Site__r.Name, Hostname__c FROM Management_IP__c WHERE Id = :value];
            }
        }
    }
    public List<ConnectedDevice> managementIPPortAssignmentResults {get;set;}
    public string searchString {get;set;}
    public Id currentDeviceId {get;set;}
    public Management_IP_Port_Assignment__c currentPortAssignment {get;set;}
    
    public ConnectedDeviceLookupController() {
        this.searchString = '';
        this.currentDeviceId = System.currentPageReference().getParameters().get('currentDeviceId');
        this.managementIPResults = this.performManagementIPSearch(this.searchString);
    }
    
    public PageReference search() {
        this.managementIPResults = this.performManagementIPSearch(searchString);
        return null;
    }
    
    public void unsetManagementIP() {
        this.managementIPId = null;
    }
    
    public PageReference setManagementIP() {
        this.managementIPPortAssignmentResults = this.performManagementIPPortAssignmentSearch('');
        return null;
    }
    
    public void createManagementIPPortAssignment () {
        Management_IP_Port_Assignment__c portAssignment = new Management_IP_Port_Assignment__c(Management_IP__c = Apexpages.currentPage().getParameters().get('curIP'), Management_Device_Type__c = Apexpages.currentPage().getParameters().get('curDeviceType'), Management_Device_Type_Port__c = Apexpages.currentPage().getParameters().get('curDevicePort'));
        insert portAssignment;
        this.currentPortAssignment = [SELECT Id, Name__c FROM Management_IP_Port_Assignment__c WHERE Id = :portAssignment.Id];
    }
    
    private List<Management_IP__c> performManagementIPSearch(String searchString) {
        String soql = 'SELECT Id, Name, Domain__c FROM Management_IP__c WHERE Active__c = true AND Id != \'' + this.currentDeviceId  + '\'';
        if (searchString != '' && searchString != null) {
            soql = soql + ' AND (Name LIKE \'%' + searchString +'%\' OR Domain__c LIKE \'%' + searchString +'%\')';
        }
        soql = soql + ' LIMIT 25';
        return database.query(soql); 
    }
    
    public List<ConnectedDevice> performManagementIPPortAssignmentSearch(String searchString) {
        
        List<ConnectedDevice> portAssignments = new List<ConnectedDevice>();
        for (Management_IP_Port_Assignment__c portAssignment : [SELECT Id, Name__c, Management_Device_Type_Port__r.Name, Description__c, Connected_Device_Name__c FROM Management_IP_Port_Assignment__c WHERE Management_IP__c = :this.managementIPId]) {
            portAssignments.add(new ConnectedDevice(portAssignment.Id, portAssignment.Name__c, portAssignment.Description__c, portAssignment.Connected_Device_Name__c));
        }
        
        String name;
        for (Management_Device_Type_Port__c port : [SELECT Id, Name FROM Management_Device_Type_Port__c WHERE Management_Device_Type__c = :this.managementIP.Device__c AND Id NOT IN (SELECT Management_Device_Type_Port__c FROM Management_IP_Port_Assignment__c WHERE Management_IP__c = :this.managementIPId)]) {
            name = this.managementIP.Site__r.Name + ' ' + this.ManagementIP.Hostname__c + ' - Port ' + port.Name;
            portAssignments.add(new ConnectedDevice(this.managementIPId, this.managementIP.Device__c, port.Id, name));
        }
        
        //portAssignments.sort();
        
        /*String soql = 'SELECT Id, Management_Device_Type_Port__r.Name, Name__c FROM Management_IP_Port_Assignment__c WHERE Management_IP__c = \'' + this.managementIPId + '\'';
        if (searchString != '' && searchString != null) {
            soql = soql + ' AND Name LIKE \'%' + searchString +'%\'';
        }
        soql = soql + ' LIMIT 25';
        System.debug(soql);
        return database.query(soql);*/
        
        return portAssignments;
    }
    
    public string getFormTag() {
        return System.currentPageReference().getParameters().get('frm');
    }
    
    public string getTextBox() {
        return System.currentPageReference().getParameters().get('txt');
    }
}