src/objects/Management_Device_Type__c.object
<CustomObject>
    <fields>
        <fullName>PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Siklu_PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Siklu PTP</label>
        <type>Checkbox</type>
    </fields>
    <label>Management Device Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PTP__c</fullName>
        <formula>Device__r.PTP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remote_Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Remote Device</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <errorMessage>Device Type must match Remote Device Type</errorMessage>
            <filterItems>
                <field>$Source.Device__c</field>
                <operation>equals</operation>
                <valueField>Management_IP__c.Device__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Management_IP__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Management_IP__c.Remote_Device__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Management_IP__c.Remote_Device__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Management_IP__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Remote_Device</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Siklu_PTP__c</fullName>
        <formula>Device__r.Siklu_PTP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Siklu PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Siklu_Rx_Link_Id__c</fullName>
        <label>Rx Link Id</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Siklu_Tx_Link_Id__c</fullName>
        <label>Tx Link Id</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Site</label>
        <referenceTo>Management_Site__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManagementIPController.cls
public class ManagementIPController {
        
    private Management_IP__c managementIP;
    public Management_IP__c clonedManagementIP {get;set;}
    public String freeIP {get;set;}
    public Decimal sikluTxLinkId {get;set;}
    public Decimal sikluRxLinkId {get;set;}
    private ApexPages.StandardController stdController;
    private Set<String> usedIPs = new Set<String>();
    private Set<Decimal> usedSikluLinkIds = new Set<Decimal>();
    
    public ManagementIPController(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        this.managementIP = (Management_IP__c)this.stdController.getRecord();
        if (this.managementIP.Id != null) {
            for (Management_IP__c temp : [SELECT Name FROM Management_IP__c WHERE Id = :this.managementIP.Id]) {
                this.managementIP.Name = temp.Name;
                break;
            }
            this.freeIP = this.managementIP.Name;
        }
        remoteDeviceChanged();
    }
    
    public PageReference cloneRecord() {
        this.clonedManagementIP = this.managementIP.clone(false, true, false, false);
        this.freeIP = ManagementSiteClass.getFreeIPAddress(this.managementIP.Site__c);
        
        return new PageReference('/apex/ManagementIPClone');
    }
    
    public void generateIP() {
        if (this.managementIP.Site__c != null) {
                usedIPs.add(this.freeIP);
                this.freeIP = ManagementSiteClass.getFreeIPAddress(this.managementIP.Site__c, usedIPs);
        }
    }
    
    public void generateSikluLinkIds() {
        if (this.managementIP.Site__c != null) {
            usedSikluLinkIds.add(this.managementIP.Siklu_Tx_Link_Id__c);
            usedSikluLinkIds.add(this.managementIP.Siklu_Rx_Link_Id__c);
            this.managementIP.Siklu_Tx_Link_Id__c = ManagementSiteClass.getFreeSikluLinkId(this.managementIP.Site__c, usedSikluLinkIds);
            usedSikluLinkIds.add(this.managementIP.Siklu_Tx_Link_Id__c);
            this.managementIP.Siklu_Rx_Link_Id__c = ManagementSiteClass.getFreeSikluLinkId(this.managementIP.Site__c, usedSikluLinkIds);
        }
    }
    
    public boolean getPTP() {
        if (this.managementIP.Device__c != null) {
            Management_Device_Type__c device = [SELECT PTP__c FROM Management_Device_Type__c WHERE Id = :this.managementIP.Device__c];
            return device.PTP__c;
        }
        return false;
    }
    
    public boolean getSikluPTP() {
        if (this.managementIP.Device__c != null) {
            Management_Device_Type__c device = [SELECT Siklu_PTP__c FROM Management_Device_Type__c WHERE Id = :this.managementIP.Device__c];
            return device.Siklu_PTP__c;
        }
        return false;
    }
    
    public void remoteDeviceChanged() {
        if (this.managementIP.Remote_Device__c != null) {
            Management_IP__c remoteDevice = [SELECT Siklu_Tx_Link_Id__c, Siklu_Rx_Link_Id__c FROM Management_IP__c WHERE Id = :this.managementIP.Remote_Device__c];
            this.sikluTxLinkId = remoteDevice.Siklu_Rx_Link_Id__c;
            this.sikluRxLinkId = remoteDevice.Siklu_Tx_Link_Id__c;
        }
    }
    
    public PageReference save() {
        this.managementIP.Name = this.freeIP;
        return this.stdController.save();
    }
    
    public PageReference saveClone() {
        this.clonedManagementIP.Name = this.freeIP;
        try {
                insert this.clonedManagementIP;
        } catch (Exception e) {
                ApexPages.addMessages(e);
                        return null;
        }
        
        return new PageReference('/' + this.clonedManagementIP.Id);
    }
        
}