src/objects/Management_Device_Type__c.object
<CustomObject>
    <fields>
        <fullName>PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Siklu_PTP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Siklu PTP</label>
        <type>Checkbox</type>
    </fields>
    <label>Management Device Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hostname__c</fullName>
        <label>Hostname</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTP__c</fullName>
        <formula>Device__r.PTP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remote_Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Remote Device</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <errorMessage>Device Type must match Remote Device Type</errorMessage>
            <filterItems>
                <field>$Source.Device__c</field>
                <operation>equals</operation>
                <valueField>Management_IP__c.Device__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.Id</field>
                <operation>notEqual</operation>
                <valueField>Management_IP__c.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Management_IP__c.Remote_Device__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Management_IP__c.Remote_Device__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Management_IP__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Remote_Device</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Siklu_Channel_Bandwidth__c</fullName>
        <label>Channel Bandwidth</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>125</fullName>
                </value>
                <value>
                    <fullName>250</fullName>
                </value>
                <value>
                    <fullName>500</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siklu_Mode__c</fullName>
        <label>Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>master</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>slave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siklu_PTP__c</fullName>
        <formula>Device__r.Siklu_PTP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Siklu PTP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Siklu_Tx_Frequency__c</fullName>
        <label>Tx Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Siklu_Channel_Bandwidth__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>71937.5</fullName>
                </value>
                <value>
                    <fullName>72062.5</fullName>
                </value>
                <value>
                    <fullName>72187.5</fullName>
                </value>
                <value>
                    <fullName>72312.5</fullName>
                </value>
                <value>
                    <fullName>72437.5</fullName>
                </value>
                <value>
                    <fullName>72562.5</fullName>
                </value>
                <value>
                    <fullName>72687.5</fullName>
                </value>
                <value>
                    <fullName>72812.5</fullName>
                </value>
                <value>
                    <fullName>72937.5</fullName>
                </value>
                <value>
                    <fullName>73062.5</fullName>
                </value>
                <value>
                    <fullName>73187.5</fullName>
                </value>
                <value>
                    <fullName>73312.5</fullName>
                </value>
                <value>
                    <fullName>73437.5</fullName>
                </value>
                <value>
                    <fullName>73562.5</fullName>
                </value>
                <value>
                    <fullName>73687.5</fullName>
                </value>
                <value>
                    <fullName>73812.5</fullName>
                </value>
                <value>
                    <fullName>73937.5</fullName>
                </value>
                <value>
                    <fullName>74062.5</fullName>
                </value>
                <value>
                    <fullName>74187.5</fullName>
                </value>
                <value>
                    <fullName>74312.5</fullName>
                </value>
                <value>
                    <fullName>74437.5</fullName>
                </value>
                <value>
                    <fullName>74562.5</fullName>
                </value>
                <value>
                    <fullName>74687.5</fullName>
                </value>
                <value>
                    <fullName>74812.5</fullName>
                </value>
                <value>
                    <fullName>74937.5</fullName>
                </value>
                <value>
                    <fullName>75062.5</fullName>
                </value>
                <value>
                    <fullName>75187.5</fullName>
                </value>
                <value>
                    <fullName>75312.5</fullName>
                </value>
                <value>
                    <fullName>75437.5</fullName>
                </value>
                <value>
                    <fullName>75562.5</fullName>
                </value>
                <value>
                    <fullName>71875</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Site</label>
        <referenceTo>Management_Site__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <formula>Site__r.Parent_Subnet__c</formula>
        <label>Subnet</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN__c</fullName>
        <formula>Site__r.Parent_VLAN__c</formula>
        <label>VLAN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_Site__c.object
<CustomObject>
    <fields>
        <fullName>Hostname__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Hostname</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Subnet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VLAN__c</fullName>
        <label>VLAN</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Management Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ValidateManagementIPTestClass.cls
@isTest
public class ValidateManagementIPTestClass {
	
    static testMethod void testValidation() {
        Management_Site__c managementSite = new Management_Site__c(Name='Test', Hostname__c='test.com', Subnet__c='10.22.0.128/25', VLAN__c=5, Latitude__c=1, Longitude__c=1, Range__c=1);
        
        insert managementSite;
        
        Management_Device_Type__c managementDevice = new Management_Device_Type__c(Name='Test Device');
        Management_Device_Type__c managementDevice2 = new Management_Device_Type__c(Name='Test Siklu Device', PTP__c=true, Siklu_PTP__c=true);
        
        insert managementDevice;
        insert managementDevice2;
        
        Management_IP__c managementIP = new Management_IP__c(Name='10.22.0.159', Hostname__c='device1', Site__c=managementSite.Id, Device__c=managementDevice.Id);
        Management_IP__c managementIP2 = new Management_IP__c(Name='10.22.0.160', Hostname__c='device1', Site__c=managementSite.Id, Device__c=managementDevice.Id);
        Management_IP__c managementIP3 = new Management_IP__c(Name='10.22.0.159', Hostname__c='device2', Site__c=managementSite.Id, Device__c=managementDevice.Id);
        Management_IP__c managementIP4 = new Management_IP__c(Name='10.22.1.159', Hostname__c='device2', Site__c=managementSite.Id, Device__c=managementDevice.Id);
        Management_IP__c managementIP5 = new Management_IP__c(Name='10.22.1159', Hostname__c='device2', Site__c=managementSite.Id, Device__c=managementDevice.Id);
        
        Management_IP__c managementIP6 = new Management_IP__c(Name='10.22.0.130', Hostname__c='siklu', Site__c=managementSite.Id, Device__c=managementDevice2.Id, Siklu_Mode__c='master', Siklu_Channel_Bandwidth__c='500', Siklu_Tx_Frequency__c='71875');
        
        insert managementIP;
        
        try {
          	insert managementIP2;
            System.assert(false);
        } catch (DMLException e) {
            
        }
        
        try {
          	insert managementIP3;
            System.assert(false);
        } catch (DMLException e) {
            
        }
        
        try {
          	insert managementIP4;
            System.assert(false);
        } catch (DMLException e) {
            
        }
        
        try {
          	insert managementIP5;
            System.assert(false);
        } catch (DMLException e) {
            
        }
        
        insert managementIP6;
        
        Management_IP__c managementIP7 = new Management_IP__c(Name='10.22.0.131', Hostname__c='siklu2', Site__c=managementSite.Id, Device__c=managementDevice2.Id, Remote_Device__c=managementIP6.Id);
        
        insert managementIP7;
        
        managementIP7.Remote_Device__c = null;
        
        update managementIP7;
        
    }
    
}