src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Siklu_Rx_Link_Id__c</fullName>
        <label>Rx Link Id</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Siklu_Tx_Link_Id__c</fullName>
        <label>Tx Link Id</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Site</label>
        <referenceTo>Management_Site__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <formula>Site__r.Parent_Subnet__c</formula>
        <label>Subnet</label>
        <type>Text</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_Site__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Subnet__c</fullName>
        <formula>IF(NOT(ISBLANK(Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c)), Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c,
IF(NOT(ISBLANK(Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c)), Parent_Site__r.Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c,
IF(NOT(ISBLANK(Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c)), Parent_Site__r.Parent_Site__r.Parent_Site__r.Subnet__c,
IF(NOT(ISBLANK(Parent_Site__r.Parent_Site__r.Subnet__c)), Parent_Site__r.Parent_Site__r.Subnet__c,
IF(NOT(ISBLANK(Parent_Site__r.Subnet__c)), Parent_Site__r.Subnet__c,
Subnet__c)))))</formula>
        <label>Subnet</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Subnet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Management Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManagementSiteClass.cls
public class ManagementSiteClass {
	
	public static String getFreeIPAddress(Id managementSiteId) {
		return ManagementSiteClass.getFreeIPAddress(managementSiteId, new Set<String>());
	}
	
    public static String getFreeIPAddress(Id managementSiteId, Set<String>excludeIps) {
    	Set<String> usedIps = new Set<String>();
    	Management_Site__c managementSite;
    	Integer curVal;
    	Integer subnetMinVal = 0;
    	Integer subnetMaxVal;
    	Integer i;
    	Integer d1;
    	Integer d2;
    	Integer d3;
    	Integer d4;
    	String ip;
    	
    	managementSite = [SELECT Id, Parent_Subnet__c FROM Management_Site__c WHERE Id = :managementSiteId];
    	
    	for (Management_IP__c managementIP : [SELECT Name FROM Management_IP__c WHERE Subnet__c = :managementSite.Parent_Subnet__c]) {
    		usedIps.add(managementIP.Name);
    	}
    	
    	String subnet = managementSite.Parent_Subnet__c.split('\\/')[0];
    	Integer mask = Integer.valueOf(managementSite.Parent_Subnet__c.split('\\/')[1]);
    	
    	for (i = 0; i < 4; i++) {
    		curVal = Integer.valueOf(subnet.split('\\.')[i]);
    		curVal = curVal << (8 * (3 - i));
    		subnetMinVal += curVal;
    	}
    	
    	if (mask > 31) {
    		subnetMaxVal = subnetMinVal;
    	} else {
	    	curVal = 1;
	    	for (i = 31; i >= mask; i--) {
	    		curVal *= 2;
	    	}
	    	subnetMaxVal = subnetMinVal + curVal - 1;
    	}
    	
    	for (i = subnetMinVal + 1; i < subnetMaxVal; i++) {
    		d4 = i >> 24;
    		d3 = (i - (d4 << 24)) >> 16;
    		d2 = (i - (d4 << 24) - (d3 << 16)) >> 8;
    		d1 = i - (d4 << 24) - (d3 << 16) - (d2 << 8);
    		ip = String.valueOf(d4) + '.' + String.valueOf(d3) + '.' + String.valueOf(d2) + '.' + String.valueOf(d1);
    		
    		if (usedIps.contains(ip)) {
    			continue;
    		}
    		
    		if (excludeIps.contains(ip)) {
    			continue;
    		}
    		
    		return ip;
    	}
    	
    	return null;
    	
    }
    
    public static Decimal getFreeSikluLinkId(Id managementSiteId) {
        return ManagementSiteClass.getFreeSikluLinkId(managementSiteId, new Set<Decimal>());
    }
    
    public static Decimal getFreeSikluLinkId(Id managementSiteId, Set<Decimal>excludeIds) {
        Set<Decimal> usedIds = new Set<Decimal>();
        
    	for (Management_IP__c managementIP : [SELECT Siklu_Tx_Link_Id__c, Siklu_Rx_Link_Id__c FROM Management_IP__c WHERE Site__c = :managementSiteId]) {
    		usedIds.add(managementIP.Siklu_Tx_Link_Id__c);
            usedIds.add(managementIP.Siklu_Rx_Link_Id__c);
    	}
        
        for (Decimal i = 1; i < 128; i++) {
            if (usedIds.contains(i)) {
                continue;
            }
            
            if (excludeIds.contains(i)) {
                continue;
            }
            
            return i;
        }
        
        return null;
    }
    
}