src/objects/Management_Site__c.object
<CustomObject>
    <fields>
        <fullName>Hostname__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Hostname</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Subnet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VLAN__c</fullName>
        <label>VLAN</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Management Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ValidateManagementSiteTestClass.cls
@isTest
public class ValidateManagementSiteTestClass {
	
    static testMethod void testValidation() {
        Management_Site__c managementSite = new Management_Site__c(Name='Test', Hostname__c='test.com', Subnet__c='10.22.0.192/26', VLAN__c=5, Latitude__c=-1, Longitude__c=-1, Range__c=1);
        Management_Site__c managementSite2 = new Management_Site__c(Name='Test2', Hostname__c='test.com2', Subnet__c='10.22.0.0/32', VLAN__c=5, Latitude__c=-1, Longitude__c=-1, Range__c=1);
        Management_Site__c managementSite3 = new Management_Site__c(Name='Test3', Hostname__c='test.com3', Subnet__c='10.22.0.0/35', VLAN__c=5, Latitude__c=-1, Longitude__c=-1, Range__c=1);
        Management_Site__c managementSite4 = new Management_Site__c(Name='Test3', Hostname__c='test.com3', Subnet__c='10.22.0.129/25', VLAN__c=5, Latitude__c=-1, Longitude__c=-1, Range__c=1);
        
        insert managementSite;
        insert managementSite2;
        
        try {
          	insert managementSite3;
            System.assert(false);
        } catch (DMLException e) {
            
        }
        
        try {
          	insert managementSite4;
            System.assert(false);
        } catch (DMLException e) {
            
        }
    }
    
}