src/objects/Management_Device_Type__c.object
<CustomObject>
    <label>Management Device Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Device Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_IP__c.object
<CustomObject>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Device Type</label>
        <referenceTo>Management_Device_Type__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hostname__c</fullName>
        <label>Hostname</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Management Site</label>
        <referenceTo>Management_Site__c</referenceTo>
        <relationshipLabel>Management IPs</relationshipLabel>
        <relationshipName>Management_IPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <formula>Site__r.Parent_Subnet__c</formula>
        <label>Subnet</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VLAN__c</fullName>
        <formula>Site__r.Parent_VLAN__c</formula>
        <label>VLAN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Management IP</label>
    <nameField>
        <label>IP Address</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management IPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Management_Site__c.object
<CustomObject>
    <fields>
        <fullName>Hostname__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Hostname</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range__c</fullName>
        <label>Range</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subnet__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Subnet</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VLAN__c</fullName>
        <label>VLAN</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Management Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManagementIPControllerTestClass.cls
@isTest
public class ManagementIPControllerTestClass {
	
    static testMethod void testManagementIPController() {
        Management_Site__c managementSite = new Management_Site__c(Name='Test', Hostname__c='test.com', Subnet__c='10.22.0.128/30', VLAN__c=5, Latitude__c=-1, Longitude__c=-1, Range__c=1);
    	insert managementSite;
        
        Management_Device_Type__c managementDeviceType = new Management_Device_Type__c(Name='test');
        insert managementDeviceType;
        
        Management_IP__c managementIP = new Management_IP__c(Name='10.22.0.129', Site__c=managementSite.Id, Hostname__c='test', Device__c=managementDeviceType.Id);
        insert managementIP;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(managementIP);
        ManagementIPController managementIPController = new ManagementIPController(stdController);
        
        managementIPController.generateIP();
        managementIPController.cloneRecord();
        managementIPController.save();
        managementIPController.saveClone();
    }
    
}