src/objects/ThingPark_Invoice_Configuration__mdt.object
<CustomObject>
    <description>Information Common to all ThingPark invoices</description>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>ThingPark Invoice Configuration</label>
    <pluralLabel>ThingPark Invoices Configuration</pluralLabel>
</CustomObject>

src/classes/ThingParkInvoiceConfig.cls
public class ThingParkInvoiceConfig {

    private ThingPark_Invoice_Configuration__mdt config;

	private ThingParkInvoiceConfig() {
        config = [SELECT label, Version__c FROM ThingPark_Invoice_Configuration__mdt WHERE label = 'Current'];
    }

    private ThingParkInvoiceConfig(final String scope) {
        config = [SELECT label, Version__c FROM ThingPark_Invoice_Configuration__mdt WHERE label = :scope];
    }

    public static ThingParkInvoiceConfig selectCurrent() {
        return new ThingParkInvoiceConfig();
    }
    
    public static ThingParkInvoiceConfig selectStable() {
        return new ThingParkInvoiceConfig('Stable');
    }

    public static ThingParkInvoiceConfig selectLatest() {
        return new ThingParkInvoiceConfig('Latest');
    }

	public String asString() {
        return JSON.serialize(config);
    }

	public void toLog() {
        System.debug('toLog : ' + asString());
    }

}