src/objects/ThingPark_REST_Config__mdt.object
<CustomObject>
    <description>Connection Settings for ThingPark REST API</description>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&apos;latest/api&apos;</defaultValue>
        <description>API Version number for Actility.</description>
        <label>API Version</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <defaultValue>&apos;connexin-api/salesforce-actility-api@connexin.co.uk&apos;</defaultValue>
        <label>Client ID</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Password__c</fullName>
        <label>Client Password</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <defaultValue>&apos;373C2US9JU131Pw&apos;</defaultValue>
        <label>Client Secret</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <defaultValue>&apos;https://dx-api.thingpark.com&apos;</defaultValue>
        <description>The Endpoint base URL.</description>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Order_JSON__c</fullName>
        <description>JSON Template for Actility Order</description>
        <label>Order JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscriber_JSON__c</fullName>
        <description>JSON Template for Actility Subscriber</description>
        <label>Subscriber JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ThingPark REST Configuration</label>
    <pluralLabel>ThingPark REST Configurations</pluralLabel>
</CustomObject>

src/classes/ThingParkRestConfig.cls
public class ThingParkRestConfig {

    private ThingPark_REST_Config__mdt config;

    public ThingParkRestConfig() {
        config = [SELECT label, API_Version__c, Client_ID__c, Client_Password__c, Client_Secret__c, Endpoint__c, Subscriber_JSON__c, Order_JSON__c FROM ThingPark_REST_Config__mdt WHERE label = 'Current'];
    }

    public ThingParkRestConfig(final String scope) {
        config = [SELECT label, API_Version__c, Client_ID__c, Client_Password__c, Client_Secret__c, Endpoint__c, Subscriber_JSON__c, Order_JSON__c FROM ThingPark_REST_Config__mdt WHERE label = :scope];
    }

    public static ThingParkRestConfig selectCurrent() {
        return new ThingParkRestConfig();
    }
    
    public static ThingParkRestConfig selectStable() {
        return new ThingParkRestConfig('Stable');
    }

    public static ThingParkRestConfig selectLatest() {
        return new ThingParkRestConfig('Latest');
    }

    public String label() {
        return config.label;
    }
    
    public String version() {
        return config.API_Version__c;
    }

    public String clientId() {
        return config.Client_ID__c;
    }

    public String clientPassword() {
        return config.Client_Password__c;
    }

    public String clientSecret() {
        return config.Client_Secret__c;
    }

    public String endpoint() {
        return config.Endpoint__c;
    }

    public String subscriberJsonTemplate() {
        return config.Subscriber_JSON__c;
    }

	public String orderJsonTemplate() {
        return config.Order_JSON__c;
    }

	public String asString() {
        return JSON.serialize(config);
    }

	public void toLog() {
        System.debug('toLog : ' + asString());
    }
}