src/objects/ThingPark_REST_Config__mdt.object
<CustomObject>
    <description>Connection Settings for ThingPark REST API</description>
    <fields>
        <fullName>API_Version__c</fullName>
        <defaultValue>&apos;latest/api&apos;</defaultValue>
        <description>API Version number for Actility.</description>
        <label>API Version</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <defaultValue>&apos;connexin-api/salesforce-actility-api@connexin.co.uk&apos;</defaultValue>
        <label>Client ID</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Password__c</fullName>
        <label>Client Password</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Secret__c</fullName>
        <defaultValue>&apos;373C2US9JU131Pw&apos;</defaultValue>
        <label>Client Secret</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <defaultValue>&apos;https://dx-api.thingpark.com&apos;</defaultValue>
        <description>The Endpoint base URL.</description>
        <label>Endpoint</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>ThingPark REST Configuration</label>
    <pluralLabel>ThingPark REST Configurations</pluralLabel>
</CustomObject>

src/classes/ThingParkConfig.cls
public class ThingParkConfig {

    private ThingPark_REST_Config__mdt config ;

    public ThingParkConfig() {
        config = [SELECT API_Version__c, Client_ID__c, Client_Password__c, Client_Secret__c, Endpoint__c FROM ThingPark_REST_Config__mdt WHERE label = 'stable'];
        System.debug('ThingParkConfig : ' + config);
    }
    
    public ThingParkConfig(final String scope) {
        config = [SELECT API_Version__c, Client_ID__c, Client_Password__c, Client_Secret__c, Endpoint__c FROM ThingPark_REST_Config__mdt WHERE label = :scope];
        System.debug('ThingParkConfig : ' + config);
    }
    
    public static ThingParkConfig selectLatest() {
        return new ThingParkConfig('latest');
    }
    
    public static ThingParkConfig selectStable() {
        return new ThingParkConfig('stable');
    }

    public String version() {
        return config.API_Version__c;
    }

    public String clientId() {
        return config.Client_ID__c;
    }

    public String clientPassword() {
        return config.Client_Password__c;
    }

    public String clientSecret() {
        return config.Client_Secret__c;
    }

    public String endpoint() {
        return config.Endpoint__c;
    } 

}